const units=[
 {title:"Welcome & baseline",time:"8 min",objective:"Understand the learning pathway and establish your baseline without affecting certification.",sections:[
  ["must","What this course certifies","This course develops recognition, interpretation and clinical decision-making. It does not by itself certify hands-on competence in bag-mask ventilation, NIV setup or intubation."],
  ["good","How mastery works","Units open sequentially. A score of 90% is required. If you miss an item, a focused explanation appears and you can try a parallel question."],
  ["nice","Choose your depth","Must Know material is compulsory. Good to Know and Nice to Know layers can be shown or hidden without losing your core progress."]],q:{stem:"Which outcome can be validly certified entirely online?",options:["Independent competence in pediatric intubation","Knowledge and clinical decision-making","Unsupervised NIV setup in every device"],answer:1,why:"Online assessment can demonstrate knowledge and clinical decision-making. Practical procedures require supervised simulation or workplace assessment."}},
 {title:"Recognise respiratory failure",time:"28 min",objective:"Differentiate respiratory distress from impending or established respiratory failure.",sections:[
  ["must","Distress is compensation","Tachypnoea, recession, nasal flaring and grunting show that the child is working to preserve gas exchange. Trend the child, not one isolated number."],
  ["must","Failure is loss of compensation","Reduced effort, altered consciousness, poor air entry, apnoea, cyanosis or bradycardia are late and dangerous signs. A falling respiratory rate can mean fatigue—not recovery."],
  ["good","Locate the problem","Stridor suggests upper-airway obstruction; wheeze suggests lower-airway narrowing; crackles and hypoxaemia suggest parenchymal disease. Mixed patterns are common."],
  ["nice","Physiological phenotypes","Respiratory failure may be predominantly hypoxaemic, hypercapnic or mixed. This distinction helps select support but must not delay stabilization."]],q:{stem:"A severely distressed child becomes quieter, drowsy and has poorer air entry. What is the safest interpretation?",options:["The child is settling","Respiratory muscle fatigue and impending failure","Oxygen has treated the underlying illness"],answer:1,why:"The apparent reduction in effort is a late warning sign. Escalate immediately while supporting airway and breathing."}},
 {title:"Oxygenation made simple",time:"32 min",objective:"Explain oxygenation, ventilation and the major mechanisms of hypoxaemia using bedside language.",sections:[
  ["must","Two different jobs","Oxygenation moves oxygen into blood. Ventilation removes carbon dioxide. A normal SpO₂ does not prove adequate ventilation."],
  ["must","Oxygen delivery needs more than SpO₂","Delivery to tissues depends on saturation, haemoglobin and cardiac output. A profoundly anaemic child can have a normal saturation but inadequate oxygen content."],
  ["good","Why oxygen sometimes fails","Low inspired oxygen, hypoventilation, V/Q mismatch and shunt cause hypoxaemia by different mechanisms. A large shunt may respond incompletely to additional oxygen."],
  ["nice","The dissociation curve","The flat upper portion provides a saturation reserve; on the steep portion, a small fall in PaO₂ can produce a rapid fall in SpO₂."]],q:{stem:"Which statement is correct?",options:["SpO₂ directly measures PaCO₂","Normal SpO₂ excludes respiratory failure","Ventilation may fail despite a normal SpO₂"],answer:2,why:"Oxygen saturation does not measure carbon-dioxide clearance. Clinical assessment and, when indicated, blood gas or CO₂ monitoring are needed."}},
 {title:"Pulse oximetry",time:"24 min",objective:"Obtain, validate and interpret pulse-oximeter readings safely.",sections:[
  ["must","Validate before acting","Check probe position, pulse agreement, signal quality and the child. Motion, cold extremities and poor perfusion can produce misleading values."],
  ["must","Treat the child","A concerning clinical picture overrides a reassuring or erratic number. Never delay airway or breathing support while trying multiple probes."],
  ["good","Know the limitations","Ambient light, nail products, skin pigmentation, dyshemoglobinaemia and venous pulsation may affect accuracy. Interpret trends and context."],
  ["nice","Beyond SpO₂","Waveform capnography and blood gases answer different questions. Select monitoring according to the physiological concern."]],q:{stem:"A shocked child has an SpO₂ of 74% with no stable waveform and a displayed pulse of 42 while the palpable pulse is 150. First action?",options:["Accept the saturation as accurate","Validate probe and signal while clinically supporting the child","Wait five minutes without intervention"],answer:1,why:"The pulse mismatch makes the reading unreliable, but the child still requires immediate clinical assessment and support."}},
 {title:"Conventional oxygen",time:"35 min",objective:"Select an appropriate oxygen source and interface, then monitor response and safety.",sections:[
  ["must","Choose by clinical need","Use an age-appropriate interface that delivers sufficient oxygen and is tolerated. Reassess saturation, effort, mental state and circulation after every change."],
  ["must","Escalate the child, not just the device","A rising oxygen requirement or worsening effort is treatment failure until proved otherwise. Call for help early."],
  ["good","Sources and interfaces","Know the capabilities and limitations of nasal prongs, simple masks, non-rebreathing masks, hoods, concentrators and cylinders available locally."],
  ["nice","Oxygen systems","Safe care also depends on supply estimation, cylinder security, fire safety, maintenance and contingency planning."]],q:{stem:"After changing an oxygen device, the best next step is to:",options:["Document it at the end of the shift","Reassess oxygenation, work of breathing and the child’s overall state","Wait for a blood gas before looking at the child"],answer:1,why:"Respiratory support is a monitored intervention. Response and deterioration must be identified promptly."}},
 {title:"Bag-mask ventilation",time:"32 min",objective:"Describe effective bag-mask ventilation and recognise ineffective or harmful technique.",sections:[
  ["must","The visible target","Position the airway, select the correct mask, create a seal and ventilate only enough to produce visible chest rise."],
  ["must","If the chest does not rise","Reposition, improve the seal, open the airway, suction when appropriate and use a two-person technique. Consider obstruction."],
  ["good","Avoid harm","Excessive pressure or rate causes gastric inflation, impaired venous return and lung injury. Coordinate compressions and ventilation according to current resuscitation guidance."],
  ["nice","Human factors","A designated airway lead, closed-loop communication and verbal confirmation of chest rise improve team performance."]],q:{stem:"The chest does not rise during bag-mask ventilation. What is the best immediate response?",options:["Squeeze harder without reassessment","Reposition the airway and improve mask seal","Increase oxygen flow only"],answer:1,why:"Correct airway position and an effective seal are the first troubleshooting steps; a two-person technique may help."}},
 {title:"High-flow nasal cannula",time:"38 min",objective:"Explain HFNC initiation, monitoring, weaning and failure recognition.",sections:[
  ["must","A monitored trial","HFNC provides heated, humidified high flow. It requires a defined indication, correctly sized interface, close reassessment and an escalation plan."],
  ["must","Failure must be recognised early","Persistent distress, worsening gas exchange, apnoea, altered sensorium or haemodynamic instability should prompt urgent escalation. HFNC must not delay intubation."],
  ["good","What to adjust","Flow mainly supports work of breathing and washout; FiO₂ is titrated to the oxygenation goal. Device-specific and local protocols govern exact settings."],
  ["nice","Weaning approaches","Some pathways reduce FiO₂ before flow; others use protocolised flow reductions. Consistency, monitoring and readiness criteria matter more than ritual."]],q:{stem:"A child on HFNC has increasing work of breathing and becomes drowsy. The priority is to:",options:["Continue unchanged for another two hours","Urgently assess for support failure and escalate","Reduce monitoring to let the child sleep"],answer:1,why:"Drowsiness with worsening effort suggests failure. Non-invasive support should never postpone definitive airway management."}},
 {title:"CPAP & non-invasive ventilation",time:"44 min",objective:"Select, monitor and troubleshoot CPAP/NIV while recognising contraindications and failure.",sections:[
  ["must","CPAP and bilevel support","CPAP provides continuous distending pressure. Bilevel NIV adds inspiratory pressure support and can assist ventilation and reduce work."],
  ["must","The child must be suitable","Ability to protect the airway, haemodynamic stability, manageable secretions, interface fit and close monitoring are fundamental. Immediate intubation needs are contraindications to delay."],
  ["good","Monitor the response","Assess effort, respiratory rate, heart rate, gas exchange, comfort, leak and synchrony. Define failure criteria before starting."],
  ["nice","Interface science","Oronasal, nasal and full-face interfaces have different leaks, dead space, pressure points and tolerability. Skin protection is part of respiratory care."]],q:{stem:"Which feature most strongly argues against persisting with NIV?",options:["The mask needs adjustment","Progressive obtundation with inability to protect the airway","Mild initial anxiety"],answer:1,why:"Loss of airway protection is a major failure signal and usually requires definitive airway management."}},
 {title:"Intubation preparation",time:"42 min",objective:"Prepare the child, team and equipment for safer pediatric intubation and post-intubation care.",sections:[
  ["must","Prepare physiology and equipment","Call skilled help, preoxygenate, anticipate hypotension, check suction and backup devices, calculate drugs carefully and assign roles."],
  ["must","Confirm and secure","Use waveform capnography when available, assess bilateral air entry and chest movement, note tube depth, secure the tube and reassess after movement."],
  ["good","The physiologically difficult airway","Severe hypoxaemia, shock, acidosis or raised intracranial pressure can make intubation dangerous even when laryngoscopy is technically easy."],
  ["nice","First-pass strategy","Optimised positioning, appropriate equipment, a clear primary and rescue plan, and a shared stop point reduce repeated attempts."]],q:{stem:"The most reliable immediate method listed for confirming tracheal placement is:",options:["Tube misting","Waveform capnography with clinical assessment","Improvement in skin colour alone"],answer:1,why:"Sustained waveform capnography, interpreted with clinical findings, is the preferred confirmation method when available."}},
 {title:"Invasive ventilation",time:"52 min",objective:"Interpret core ventilator variables and create a safe initial assessment plan.",sections:[
  ["must","Know the controls","FiO₂ and mean airway pressure influence oxygenation; minute ventilation influences CO₂ clearance. PEEP, tidal volume, rate and inspiratory time interact."],
  ["must","Reassess after connection","Look at the child, chest movement, exhaled tidal volume, pressures, saturation, CO₂, circulation and alarms. Confirm settings and tube position."],
  ["good","Resistance and compliance","Obstructive disease raises resistance and risks air trapping. Stiff lungs have reduced compliance and need a lung-protective strategy."],
  ["nice","Pressure versus volume targeting","Each has advantages and limitations. Understand what the ventilator guarantees, what varies and how leaks affect delivery."]],q:{stem:"Immediately after placing a child on a ventilator, which assessment is most appropriate?",options:["Review only the set tidal volume","Assess child, tube, delivered volumes, pressures, gas exchange and circulation","Silence all alarms until the blood gas returns"],answer:1,why:"Ventilator safety requires an integrated patient–airway–device assessment, not reliance on a single displayed setting."}},
 {title:"Sudden deterioration: DOPE",time:"36 min",objective:"Respond systematically when a ventilated child deteriorates.",sections:[
  ["must","DOPE","Consider Displacement, Obstruction, Pneumothorax and Equipment failure immediately while supporting oxygenation and ventilation."],
  ["must","The patient comes first","Call for help. If ventilator function or the circuit is uncertain, disconnect and provide appropriate manual ventilation while assessing resistance and chest rise."],
  ["good","Read the alarm in context","High pressure suggests resistance, obstruction, coughing, low compliance or pneumothorax. Low pressure suggests disconnection, leak or displacement."],
  ["nice","Waveform clues","Failure of expiratory flow to return to baseline suggests air trapping. Trends in pressure, volume and flow can identify problems before a crisis."]],q:{stem:"A ventilated child suddenly desaturates and the cause is unclear. Which framework is appropriate?",options:["FAST","DOPE","AMPLE only"],answer:1,why:"DOPE prompts immediate evaluation for displacement, obstruction, pneumothorax and equipment failure."}},
 {title:"Capstone & certificate",time:"25 min",objective:"Integrate recognition, escalation and troubleshooting across a deteriorating-child pathway.",sections:[
  ["must","Think in cycles","Assess → intervene → reassess. State what improvement should look like and how soon you expect it."],
  ["good","Escalation is a treatment","Calling skilled help, preparing equipment and arranging PICU transfer are active clinical interventions—not administrative afterthoughts."],
  ["nice","Continue learning","Online mastery is the gateway to supervised device stations, simulation and workplace assessment."]],q:{stem:"Which pattern best represents safe respiratory support?",options:["Choose a device and wait","Assess, intervene, define response, reassess and escalate if needed","Treat SpO₂ without evaluating the child"],answer:1,why:"Safe support is a continuous clinical cycle with predefined response and failure criteria."}}
];
const state=JSON.parse(localStorage.getItem('vikkypaedia-oxyvent-state')||'{"done":[],"scores":{},"role":"ug","levels":["must","good","nice"]}');let current=-1;
const main=document.getElementById('main'),list=document.getElementById('unitList'),sidebar=document.getElementById('sidebar');
function save(){localStorage.setItem('vikkypaedia-oxyvent-state',JSON.stringify(state));updateProgress()}
function updateProgress(){const n=state.done.length;document.getElementById('progressText').textContent=`${n} of ${units.length} units`;document.getElementById('progressFill').style.width=`${n/units.length*100}%`;renderNav()}
function renderNav(){list.innerHTML='';units.forEach((u,i)=>{let b=document.createElement('button');b.className='unit-btn '+(current===i?'active ':'')+(state.done.includes(i)?'done':'');b.disabled=i>0&&!state.done.includes(i-1);b.innerHTML=`<span class="unit-num">${state.done.includes(i)?'✓':i+1}</span><span class="unit-title">${u.title}</span>`;b.onclick=()=>showUnit(i);list.appendChild(b)});const sb=document.createElement('button');sb.className='unit-btn '+(current===99?'active':'');sb.innerHTML='<span class="unit-num">◎</span><span class="unit-title">Certificate & evidence</span>';sb.onclick=showCertificate;list.appendChild(sb)}
function showHome(){current=-1;renderNav();main.innerHTML=`<section class="welcome"><div class="eyebrow">Mastery-based pediatric respiratory care</div><h1>See the child.<br>Support the breath.</h1><p>A self-paced clinical course from recognition and oxygen delivery to non-invasive and invasive ventilation. Learn in layers, practise decisions and remediate until you reach mastery.</p><button class="primary" onclick="showUnit(0)">Begin my pathway →</button></section><div class="start-grid"><section class="panel"><h2>Choose the depth you want to see</h2><div class="level-pills">${[['must','Must Know'],['good','Good to Know'],['nice','Nice to Know']].map(x=>`<button class="pill ${state.levels.includes(x[0])?'on':''}" onclick="toggleLevel('${x[0]}')">${x[1]}</button>`).join('')}</div></section><section class="panel"><h2>Your standard</h2><p><strong>90% mastery</strong><br><span style="color:var(--muted)">plus all safety-critical decisions.</span></p></section></div>`}
function toggleLevel(l){if(l==='must')return;state.levels=state.levels.includes(l)?state.levels.filter(x=>x!==l):[...state.levels,l];save();current<0?showHome():showUnit(current)}
function showUnit(i){current=i;sidebar.classList.remove('open');renderNav();const u=units[i];main.innerHTML=`<article class="lesson"><div class="lesson-head"><div><div class="eyebrow">Unit ${i+1} · ${i<6?'Foundations':i<9?'Non-invasive support':'Advanced support'}</div><h1>${u.title}</h1></div><span class="time">◷ ${u.time}</span></div><p class="objective">${u.objective}</p>${u.sections.filter(s=>state.levels.includes(s[0])).map(s=>`<section class="content-card"><span class="level ${s[0]}">${s[0]} to know</span><h2>${s[1]}</h2><p>${s[2]}</p></section>`).join('')}<section class="content-card scenario"><span class="level must">Mastery check</span><h2>Make the bedside decision</h2><div class="question"><p>${u.q.stem}</p><div class="options">${u.q.options.map((o,j)=>`<button class="option" onclick="answer(${i},${j},this)">${o}</button>`).join('')}</div><div class="feedback" id="feedback"></div></div></section><div class="footer-actions"><span class="mastery">${state.done.includes(i)?'✓ Mastered · '+state.scores[i]+'%':'Score 90% to unlock the next unit'}</span><button class="secondary" onclick="showHome()">Course home</button></div></article>`;window.scrollTo({top:0,behavior:'smooth'})}
function answer(i,j,el){document.querySelectorAll('.option').forEach(x=>x.classList.remove('chosen'));el.classList.add('chosen');const ok=j===units[i].q.answer,f=document.getElementById('feedback');f.className='feedback show '+(ok?'':'wrong');f.innerHTML=ok?`<strong>Correct — 100% mastery.</strong> ${units[i].q.why} <div style="margin-top:12px"><button class="primary" onclick="completeUnit(${i})">${i===units.length-1?'Complete course':'Open next unit'} →</button></div>`:`<strong>Not yet.</strong> ${units[i].q.why}<div class="callout"><strong>Focused remediation:</strong> Re-read the Must Know cards above, then select the safest bedside action. You can retry immediately.</div>`}
function completeUnit(i){if(!state.done.includes(i))state.done.push(i);state.scores[i]=100;save();i<units.length-1?showUnit(i+1):showCertificate()}
function showCertificate(){current=99;renderNav();sidebar.classList.remove('open');const eligible=state.done.length===units.length;main.innerHTML=`<section class="lesson"><div class="eyebrow">Vikkypaedia OxyVent Module</div><h1>Certificate & evidence</h1>${eligible?`<div class="certificate"><div class="eyebrow">Certificate of mastery</div><h1>Vikkypaedia OxyVent Module</h1><p>This certifies that</p><div class="name" contenteditable="true" aria-label="Enter learner name">Learner name</div><p>completed the pediatric oxygenation and ventilation knowledge and clinical decision-making pathway<br>with a mastery score of <strong>100%</strong>.</p><p><small>This online certificate does not replace supervised procedural competency assessment.</small></p><button class="primary" onclick="window.print()">Print certificate</button></div>`:`<div class="content-card cert-lock"><h2>${state.done.length}/${units.length} units mastered</h2><p>Complete every unit at 90% or above to open your certificate.</p><button class="primary" onclick="showUnit(${Math.min(state.done.length,units.length-1)})">Continue learning →</button></div>`}<section class="content-card source-list"><span class="level good">Evidence library</span><h2>Core sources</h2><ul><li><a href="https://www.who.int/publications/i/item/9789241549554" target="_blank" rel="noopener">WHO — Oxygen therapy for children</a></li><li><a href="https://www.who.int/publications/i/item/9789241510219" target="_blank" rel="noopener">WHO — Paediatric emergency triage, assessment and treatment</a></li><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9848214/" target="_blank" rel="noopener">PALICC-2 — Pediatric acute respiratory distress syndrome</a></li><li><a href="https://www.aarc.org/resource/clinical-practice-guidelines/" target="_blank" rel="noopener">AARC — Clinical practice guidelines</a></li><li><a href="https://www.who.int/publications/i/item/9789241516914" target="_blank" rel="noopener">WHO/UNICEF — Oxygen therapy devices</a></li></ul><div class="callout"><strong>Clinical governance:</strong> Thresholds, device settings and drug guidance must be reviewed against current national, institutional and manufacturer protocols before institutional release.</div></section></section>`;window.scrollTo({top:0,behavior:'smooth'})}
document.getElementById('roleSelect').value=state.role;document.getElementById('roleSelect').onchange=e=>{state.role=e.target.value;save()};document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');window.showUnit=showUnit;window.showHome=showHome;window.toggleLevel=toggleLevel;window.answer=answer;window.completeUnit=completeUnit;window.showCertificate=showCertificate;showHome();updateProgress();
