'use strict';
// Module Builder patterns adapted for OxyVent's ten-question and critical-error policy.
const C=window.COURSE,K=window.OxyCore,app=document.getElementById('app');
let storage;
try{storage=window.localStorage;}catch{storage={getItem(){throw Error('Unavailable');},setItem(){throw Error('Unavailable');}};}
const loaded=K.load(storage,C);
let state=loaded.state,storageOK=loaded.available,notice=loaded.message,pending={},drawerOpen=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=id=>C.units.find(u=>u.id===id),sourceMap=Object.fromEntries(C.sources.map(s=>[s.id,s]));
const depthLabels={must:'Must Know',good:'Must + Good to Know',nice:'All learning depths'},rank={must:0,good:1,nice:2};
function save(){storageOK=K.save(storage,state);if(!storageOK)notice='Progress could not be saved. Continue in this session and export My record before leaving.';}
function route(){try{return decodeURIComponent(location.hash.slice(1))||'home';}catch{return 'not-found';}}
function go(r){pending={};closeDrawer(false);if(route()===r)render();else location.hash=r;}
function button(text,to,kind='primary'){return `<a class="btn ${kind}" href="#${esc(to)}">${esc(text)}</a>`;}
function heading(k,t,p=''){return `<header class="page-heading"><p class="eyebrow">${esc(k)}</p><h1 tabindex="-1">${esc(t)}</h1>${p?`<p class="lead">${esc(p)}</p>`:''}</header>`;}
function refs(ids=[]){return `<div class="references">${[...new Set(ids)].map(id=>sourceMap[id]).filter(Boolean).map(s=>`<a href="${esc(s.url)}" ${s.url.startsWith('http')?'target="_blank" rel="noopener"':''}>${esc(s.organization)} · ${esc(s.title)} ↗</a>`).join('')}</div>`;}
function nextUnit(){return C.units.find(u=>K.unlocked(state,C,u)&&!K.mastered(state,u));}
function status(u){return K.mastered(state,u)?'Mastered':K.latest(state,u)?'Review needed':K.unlocked(state,C,u)?'Ready':'Locked';}
function render(focus=true){const r=route(),unit=byId(r.split('/')[1]),n=C.units.filter(u=>K.mastered(state,u)).length;
 app.innerHTML=`<header class="topbar"><button id="menuBtn" class="menu-btn" aria-label="Open course navigation" aria-controls="sidebar" aria-expanded="false">☰</button><a class="brand" href="#home"><span class="brand-mark">O₂</span><span>Vikkypaedia<small>OXYVENT · CLINICAL LEARNING</small></span></a><span class="top-label">See the child. Support the breath.</span><a class="top-progress" href="#record" aria-label="${n} of ${C.units.length} units mastered">${n}/${C.units.length}<span class="progress-track"><i style="width:${n/C.units.length*100}%"></i></span></a></header><div class="layout"><aside id="sidebar" class="sidebar" aria-label="Course navigation"><div class="side-title"><strong>Your learning path</strong><button id="closeMenu" aria-label="Close course navigation">×</button></div><label for="role">Learning as</label><select id="role">${Object.entries(C.roles).map(([v,t])=>`<option value="${v}" ${state.role===v?'selected':''}>${esc(t)}</option>`).join('')}</select><label for="depth">Learning depth</label><select id="depth">${Object.entries(depthLabels).map(([v,t])=>`<option value="${v}" ${state.depth===v?'selected':''}>${t}</option>`).join('')}</select><p class="side-help">Assessed core stays visible. Your role adds a practical responsibility lens.</p><nav><a class="nav-link ${r==='home'?'active':''}" href="#home">Your course map</a><a class="nav-link" href="#baseline">Optional clinical baseline</a>${C.units.map((u,i)=>`<a class="nav-link unit-link ${unit===u?'active':''} ${!K.unlocked(state,C,u)?'locked':''}" href="#learn/${u.id}" ${unit===u?'aria-current="page"':''}><span class="unit-number">${K.mastered(state,u)?'✓':String(i+1).padStart(2,'0')}</span><span>${esc(u.title)}<small>${status(u)}</small></span></a>`).join('')}<div class="nav-divider"></div>${[['cases','Patient journeys'],['record','My learning record'],['toolkit','Bedside learning toolkit'],['sources','Evidence library'],['about','About this edition']].map(([v,t])=>`<a class="nav-link ${r===v?'active':''}" href="#${v}">${t}</a>`).join('')}</nav><p class="side-help">90% + no safety-critical errors.<br>Progress stays in this browser.</p></aside><button id="scrim" class="scrim" aria-label="Close course navigation" hidden></button><main id="main" tabindex="-1">${notice?`<div class="notice" role="status">${esc(notice)}</div>`:''}${page(r)}<footer>OxyVent · ${C.version} · Educational edition. Independent clinical review pending. Online performance does not establish procedural competence. <a href="#about">Scope & review notes</a></footer></main></div>`;
 bind();syncDrawer();if(focus){document.querySelector('main h1')?.focus({preventScroll:true});window.scrollTo(0,0);}const anchor=r.split('/')[2];if(anchor){const target=document.getElementById('section-'+anchor),h=target?.querySelector('h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});target.scrollIntoView({block:'start'});}}
}
function page(r){if(r.startsWith('learn/')||r.startsWith('assessment/')||r.startsWith('result/')){const [kind,id,anchor]=r.split('/'),u=byId(id);if(!u)return notFound();if(!K.unlocked(state,C,u))return locked(u);return kind==='learn'?lesson(u,anchor):kind==='assessment'?assessment(u):resultPage(u);}if(r.startsWith('case/')){const c=C.cases.find(c=>c.id===r.split('/')[1]);return c?casePage(c):notFound();}return ({home,baseline,record,toolkit,sources:sourcesPage,about,cases:caseLibrary}[r]||notFound)();}
function home(){const n=C.units.filter(u=>K.mastered(state,u)).length,next=nextUnit();return `<section class="hero"><div><p class="eyebrow">PEDIATRIC RESPIRATORY LEARNING</p><h1 tabindex="-1">See the child.<br>Support the breath.</h1><p>From the first concerning observation to a safe escalation plan. Learn through patients, physiology and decisions.</p><div class="actions">${button(next?`${state.active[next.id]?'Resume':'Continue with'} ${next.title}`:'Review your achievement',next?`${state.active[next.id]?'assessment':'learn'}/${next.id}`:'record')}${button('Check your starting point','baseline','ghost')}</div></div><div class="hero-art" aria-hidden="true"><svg viewBox="0 0 240 180"><path d="M120 20v66m0-16L92 98m28-28 28 28M104 36C65 32 40 77 39 121c0 41 55 34 65 18V36Zm32 0c39-4 64 41 65 85 0 41-55 34-65 18V36Z" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg><span>ASSESS · INTERVENE · REASSESS</span></div></section><div class="stats"><div><b>${n}<small> / ${C.units.length}</small></b><span>Units currently mastered</span></div><div><b>2</b><span>Clinical forms per unit</span></div><div><b>90%<small> + safety</small></b><span>Clear progression criteria</span></div></div><section class="intro-grid"><div class="card"><p class="eyebrow">YOUR ${esc(C.roles[state.role])} PATH</p><h2>Build a decision you can explain.</h2><p>Worked examples, core teaching and ten decisions per unit. Change your role to see its responsibilities; deeper layers add context without hiding assessed essentials.</p><p class="small">About ${C.units.reduce((n,u)=>n+u.minutes,0)} minutes, plus retries. Estimates await learner-pilot validation.</p></div><div class="card soft"><h2>How progression works</h2><p>Reach 9/10 with no safety-critical errors. A finished retry updates current readiness; your first attempt remains in My record. Explain-back checks track study completion separately.</p><a href="#about">Read the learning rules →</a></div></section><div class="section-heading"><p class="eyebrow">THE COMPLETE PATHWAY</p><h2>One connected clinical story.</h2></div><div class="course-map">${C.units.map((u,i)=>`<article class="course-row"><span class="map-number">${String(i+1).padStart(2,'0')}</span><div><span class="tag">${status(u)}</span><h3>${esc(u.title)}</h3><p>${esc(u.subtitle)}</p><small>${u.minutes} min · ${u.questions.length} decisions · ${esc(u.phase)}</small></div>${button(K.unlocked(state,C,u)?'Open unit →':'View prerequisite',`learn/${u.id}`,'secondary')}</article>`).join('')}</div>`;}
function locked(u){const p=C.units.find(x=>!K.mastered(state,x));return heading('A prerequisite comes first',u.title,'Earlier units must meet the score and safety standard.')+`<div class="card"><h2>Continue with ${esc(p.title)}</h2><p>A failed completed reassessment marks current readiness for review. Earlier achievements remain in My record.</p>${button('Open prerequisite',`learn/${p.id}`)} ${button('Course map','home','secondary')}</div>`;}
function notFound(){return heading('Course navigation','This page is not available')+button('Return to your course map','home');}
function lesson(u,anchor){const shown=u.sections.filter(s=>rank[s.depth]<=rank[state.depth]);return heading(`UNIT ${C.units.indexOf(u)+1} · ${u.phase} · ${u.minutes} MIN`,u.title,u.subtitle)+`<div class="card outcomes"><p class="eyebrow">BY THE END, YOU CAN</p><ul>${u.outcomes.map(o=>`<li>${esc(o)}</li>`).join('')}</ul></div><div class="role-card"><span class="tag">${esc(C.roles[state.role])}</span><h2>Your responsibility in this unit</h2><p>${esc(u.roleNotes[state.role])}</p></div>${visual(u.visual)}<nav class="lesson-index" aria-label="On this page">${shown.map(s=>`<a href="#learn/${u.id}/${s.id}">${esc(s.title)}</a>`).join('')}</nav>${shown.map((s,i)=>`<section class="lesson-card card ${anchor===s.id?'highlight':''}" id="section-${s.id}"><div class="card-kicker"><span class="tag">${{must:'Must Know',good:'Good to Know',nice:'Nice to Know'}[s.depth]}</span><span>${String(i+1).padStart(2,'0')}</span></div><h2>${esc(s.title)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${s.points?.length?`<ul>${s.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>`:''}${refs(s.sourceIds)}<label class="checkline"><input type="checkbox" data-check="${s.id}" ${state.checks[s.id]?'checked':''}><span>I can explain the key decision in my own words.</span></label></section>`).join('')}${shown.length<u.sections.length?`<button class="btn secondary" data-depth-all>Show ${u.sections.length-shown.length} deeper section(s)</button>`:''}<section class="card"><h2>Pause and explain</h2><label for="reflection">${esc(u.reflection)}</label><textarea id="reflection" data-note="${u.id}" maxlength="4000" placeholder="A brief learning note—no patient-identifying details">${esc(state.notes[u.id]||'')}</textarea><p class="small" id="note-status">Stored only in this browser.</p></section><section class="assessment-cta"><p class="eyebrow">PUT THE LEARNING TO WORK</p><h2>${u.sequential?'Follow an unfolding patient':'Make ten clinical decisions'}</h2><p>Choose, rate confidence, then submit. Feedback explains your choice and points back to teaching.</p><p>${K.history(state,u).length>=2?'Both forms have been available. Further attempts repeat those forms: practice, not unseen assessment.':'Two authored clinical forms alternate between attempts. Options change position; reasoning matters.'}</p><button class="btn primary" data-start="${u.id}">${state.active[u.id]?'Resume saved assessment':K.latest(state,u)?'Start reassessment':'Start assessment'} →</button> ${K.latest(state,u)?button('Latest result',`result/${u.id}`,'ghost'):''}</section><div class="actions">${button('← Course map','home','secondary')}${C.units[C.units.indexOf(u)+1]&&K.mastered(state,u)?button('Open next unit →',`learn/${C.units[C.units.indexOf(u)+1].id}`):''}</div>`;}
function questionHtml(q,response,order,context){order||=q.options.map(o=>o.id);const p=pending[q.id]||{};return `<section class="question card" data-q="${q.id}"><div class="card-kicker"><span class="tag">${q.critical?'Safety-critical decision':'Clinical reasoning'}</span><span>${response?'Answer recorded':'Commit before feedback'}</span></div><h2>${esc(q.stem)}</h2>${response?`<p><b>Your answer:</b> ${esc(q.options.find(o=>o.id===response.choice)?.text)}</p><p><b>Best answer:</b> ${esc(q.options.find(o=>o.id===q.answer).text)}</p>`:`<fieldset><legend class="sr-only">Choose one answer</legend>${order.map((id,i)=>{const o=q.options.find(o=>o.id===id);return `<label class="option"><input type="radio" name="answer-${q.id}" value="${o.id}" ${p.choice===o.id?'checked':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></label>`;}).join('')}</fieldset><div class="confidence-row"><label for="conf-${q.id}">How sure are you?<select id="conf-${q.id}" data-confidence="${q.id}"><option value="">Select confidence</option>${[[1,'Guessing'],[2,'Partly sure'],[3,'Confident']].map(([v,t])=>`<option value="${v}" ${p.confidence===v?'selected':''}>${t}</option>`).join('')}</select></label><button class="btn primary" data-submit="${q.id}" data-context="${context}">Submit decision</button></div><p class="error" id="error-${q.id}" role="alert"></p>`}${response?`<div class="feedback ${response.choice===q.answer?'correct':'incorrect'}" role="status"><strong>${response.choice===q.answer?'Correct decision':'Review this decision'}</strong><p>${esc(q.options.find(o=>o.id===response.choice)?.feedback)}</p><p>${esc(q.why)}</p></div><details><summary>Why the other choices differ</summary>${q.options.map(o=>`<p><b>${esc(o.text)}</b><br>${esc(o.feedback)}</p>`).join('')}</details>${q.sectionId?button('Review the exact teaching →',`learn/${context.split(':')[1]}/${q.sectionId}`,'text'):''}${refs(q.sourceIds)}`:''}</section>`;}
function assessment(u){const a=state.active[u.id];if(!a)return heading('Assessment',u.title,'Start from the lesson to choose a new form.')+`<button class="btn primary" data-start="${u.id}">Start assessment</button>`;const pos=a.feedback?a.responses.length-1:a.responses.length,q=u.questions.flatMap(p=>p.variants).find(q=>q.id===a.order[pos]);if(!q)return resultPage(u);return heading(`FORM ${a.form.toUpperCase()} · QUESTION ${pos+1} OF ${a.order.length}`,u.title,u.sequential?'An original fictional patient. Each decision reveals the next stage.':'Your attempt is saved as you go. Return to teaching whenever you need it.')+`<div class="quiz-progress" role="progressbar" aria-label="Questions answered" aria-valuemin="0" aria-valuemax="${a.order.length}" aria-valuenow="${a.responses.length}"><i style="width:${a.responses.length/a.order.length*100}%"></i></div>${questionHtml(q,a.feedback?a.responses[pos]:null,a.optionOrder[q.id],`unit:${u.id}`)}${a.feedback?`<button class="btn primary" data-next="${u.id}">${a.responses.length===a.order.length?'See your result':'Next decision'} →</button>`:''}<div class="actions">${button('Return to teaching',`learn/${u.id}`,'secondary')}<span class="small">${storageOK?'Progress saved on this device':'Session only · storage unavailable'}</span></div>`;}
function resultPage(u){const h=K.history(state,u),s=K.summarize(u,h.at(-1));if(!s)return heading('Learning record','No completed attempt yet')+button('Open lesson',`learn/${u.id}`);const next=C.units[C.units.indexOf(u)+1];return heading(s.passed?'CURRENT MASTERY ACHIEVED':'FOCUSED REVIEW',u.title,s.passed?'You reached the score and safety standard.':s.criticalMiss?'A safety-critical decision needs review, regardless of the overall score.':'Review missed concepts, then apply them in the alternate form.')+`<div class="result-card"><strong>${s.percent}%</strong><div>${s.correct}/${s.total} correct<br>${s.criticalMiss?'Safety-critical error recorded':'No safety-critical errors'}<br>First complete attempt: ${K.summarize(u,h[0]).percent}% · Best: ${Math.max(...h.map(a=>K.summarize(u,a).percent))}%</div></div>${s.missed.length?`<section class="card"><h2>Your focused review</h2>${s.missed.map(q=>`<div class="remediation"><h3>${esc(q.stem)}</h3><p>${esc(q.why)}</p>${button('Review this concept',`learn/${u.id}/${q.sectionId}`,'secondary')}</div>`).join('')}</section>`:''}<div class="actions">${s.passed?button(next?'Continue to next unit':'View completion record',next?`learn/${next.id}`:'record'):''}<button class="btn secondary" data-start="${u.id}">Try ${h.length>=2?'a repeated':'the alternate'} form</button>${button('Review unit',`learn/${u.id}`,'secondary')}</div>`;}
function baseline(){return heading('OPTIONAL · DOES NOT CHANGE PROGRESSION','Find your starting point','Three decisions to surface your assumptions. Initial responses stay visible; these do not count toward unit mastery.')+C.baseline.map(q=>questionHtml(q,state.baseline[q.id],null,'baseline')).join('')+button('Begin the learning pathway',`learn/${C.units[0].id}`);}
function caseLibrary(){return heading('ORIGINAL FICTIONAL PATIENTS','Practice across a changing situation','Guided journeys are separate from scored unit attempts. Correct each decision to reveal the next stage.')+`<div class="case-grid">${C.cases.map(c=>`<article class="card"><p class="eyebrow">${esc(c.setting)}</p><h2>${esc(c.title)}</h2><p>${esc(c.intro)}</p>${button('Enter patient journey',`case/${c.id}`)}</article>`).join('')}</div>`;}
function casePage(c){let i=c.steps.findIndex(q=>state.cases[q.id]?.choice!==q.answer||!state.cases[q.id]?.acknowledged);const done=i<0;if(done)i=c.steps.length-1;const q=c.steps[i],r=state.cases[q.id];return heading(`PATIENT JOURNEY · STEP ${i+1}/${c.steps.length}`,c.title,c.intro)+questionHtml(q,r,null,'case')+(r&&r.choice!==q.answer?`<button class="btn secondary" data-case-retry="${q.id}">Reconsider this decision</button>`:'')+(r&&r.choice===q.answer&&!done?`<button class="btn primary" data-case-next="${q.id}">${i===c.steps.length-1?'Read the debrief':'Reveal the next stage'} →</button>`:'')+(done?`<section class="card soft"><h2>Debrief</h2><p>${esc(c.debrief)}</p>${refs(c.sourceIds)}</section>`:'')+button('All patient journeys','cases','secondary');}
function record(){const n=C.units.filter(u=>K.mastered(state,u)).length;return heading('YOUR LOCAL LEARNING RECORD','Progress with an honest history','First attempt and current readiness answer different questions. This is a self-directed record, not an accredited or independently verified certificate.')+`<div class="actions"><button class="btn primary" id="exportRecord">Download learning record</button><button class="btn secondary" id="printRecord">Print record</button><button class="btn secondary" id="resetRecord">Reset this edition’s progress</button></div><div class="table-wrap"><table><caption>Assessment and study completion by unit</caption><thead><tr><th>Unit</th><th>First</th><th>Latest</th><th>Best</th><th>Current status</th></tr></thead><tbody>${C.units.map(u=>{const h=K.history(state,u),last=K.latest(state,u);return `<tr><th><a href="#learn/${u.id}">${esc(u.title)}</a></th><td>${h.length?K.summarize(u,h[0]).percent+'%':'—'}</td><td>${last?last.percent+'%':'—'}</td><td>${h.length?Math.max(...h.map(a=>K.summarize(u,a).percent))+'%':'—'}</td><td>${status(u)}${last?.criticalMiss?' · critical review':''}${state.active[u.id]?' · attempt in progress':''}${K.complete(state,u)?' · explain-back complete':''}<small>${h.length} completed attempt(s)</small></td></tr>`;}).join('')}</tbody></table></div><section class="card"><h2>Confidence calibration</h2>${confidenceSummary()}<p class="small">Confidence is a reflection aid, not a credential.</p></section>${n===C.units.length?`<section class="certificate"><p class="eyebrow">SELF-DIRECTED COMPLETION RECORD</p><h2>Vikkypaedia OxyVent</h2><p>All ${n} units currently meet the 90% and safety standard.</p><p>Edition ${C.version} · Last assessment: ${esc(K.history(state,C.units.at(-1)).at(-1)?.finished?.slice(0,10))}</p><p>Online knowledge and fictional-case decisions. No procedural competence, accreditation or authority to practice is conferred.</p></section>`:`<div class="card soft"><h2>${n} of ${C.units.length} units currently mastered</h2>${button('Continue learning',`learn/${nextUnit()?.id||C.units[0].id}`)}</div>`}${state.legacy?`<details><summary>Previous-edition archive</summary><p>${Number(state.legacy.completed)||0} previously completed units. These results were not converted into passes on the revised assessment.</p></details>`:''}`;}
function confidenceSummary(){const items=C.units.flatMap(u=>{const h=K.history(state,u);return h.length?h[0].responses.filter(r=>r.confidence===3&&u.questions.flatMap(p=>p.variants).find(q=>q.id===r.id)?.answer!==r.choice).map(r=>({u,q:u.questions.flatMap(p=>p.variants).find(q=>q.id===r.id)})):[];});return items.length?`<p>${items.length} confident first-attempt error(s):</p><ul>${items.map(({u,q})=>`<li><a href="#learn/${u.id}/${q.sectionId}">${esc(q.stem)}</a></li>`).join('')}</ul>`:'<p>No confident errors in completed first attempts so far. Unattempted units have not been evaluated.</p>';}
function sourcesPage(){return heading('EVIDENCE & PROVENANCE','Know where a recommendation comes from','Each source records the scope actually inspected, its setting and limitations.')+`<div class="source-grid">${C.sources.map(s=>`<article class="card"><p class="eyebrow">${esc(s.organization)} · ${esc(s.id)}</p><h2><a href="${esc(s.url)}" ${s.url.startsWith('http')?'target="_blank" rel="noopener"':''}>${esc(s.title)} ↗</a></h2><p><b>Version:</b> ${esc(s.version)}</p><p><b>Checked:</b> ${esc(s.checkedOn)}</p><p><b>Inspected scope:</b> ${esc(s.scope)}</p><p><b>Limitations:</b> ${esc(s.caveat)}</p></article>`).join('')}</div>`;}
function toolkit(){return heading('TAKE THE THINKING WITH YOU','Bedside learning toolkit','Educational prompts for supervised practice. Apply approved local protocols.')+`<div class="card"><h2>Oxygen and support handover</h2><ol><li>Child, age, condition and concerning trend.</li><li>Target, source, interface, flow/FiO₂ and current support.</li><li>Response: effort, air entry, consciousness, SpO₂ and circulation.</li><li>Failure criteria, next reassessment and who is responding.</li><li>Transport gas, power, monitoring, backup and receiving team.</li></ol>${refs(['rch-oxygen','aha-als'])}</div><div class="card"><h2>Supervised BMV observation checklist</h2><ul><li>Recognizes inadequate breathing and calls for help.</li><li>Prepares equipment, position, airway and mask seal.</li><li>Delivers breaths with visible chest rise at the appropriate rate/context.</li><li>Reassesses heart rate, chest movement and response.</li><li>Corrects ineffective seal/airway; uses two-person support when available.</li><li>Avoids excessive ventilation and communicates clearly.</li></ul><p>A trained assessor must observe the performance. This is a learning aid, not a validated competency instrument.</p>${refs(['aha-bls','aha-als'])}</div><div class="card"><h2>Learn without a connection</h2><p>The single-file edition includes lessons, visuals and assessments. External references need internet. Progress belongs to the browser/file context and does not automatically sync with this website.</p><a class="btn primary" href="offline.html" download="OxyVent-offline.html">Download offline course</a></div><button class="btn secondary" id="printRecord">Print learning prompts</button>`;}
function about(){return heading('EDITION '+C.version,'A course for clinical learning','Recognition, interpretation, reassessment and escalation in pediatric respiratory care.')+`<section class="card"><h2>Scope</h2><p>Online fictional cases and knowledge questions do not assess independent BMV, NIV setup, intubation or bedside performance. Newborn resuscitation and drug prescribing are outside scope.</p><h2>Learning rules</h2><p>Ten questions per unit, two clinical forms, 90% with no critical errors. Forms alternate; further attempts repeat them. Latest complete performance determines current mastery. First and best results remain visible. Explain-back checks describe study completion separately.</p><h2>Clinical review</h2><p>Sources were checked on 15 September 2026 within the scope in Evidence library. This educational revision awaits independent pediatric clinician review and learner-pilot review. Local targets, devices and responsibilities require local approval before operational use.</p><h2>Privacy</h2><p>No account or analytics. Progress is local; do not enter patient-identifying details. Download your record before changing browsers or clearing storage.</p><h2>Design lineage</h2><p>Uses the user’s Module Builder patterns: source-linked data, role application, confidence-rated decisions, honest learning records and generated offline delivery.</p></section>`;}
function visual(kind){if(!kind)return '';if(kind==='waveform')return `<figure class="visual-card"><figcaption><b>Read the end of expiration</b><span>Schematic flow–time curves, not real patient data</span></figcaption><div class="wave-grid">${[['Complete expiration','M15 75 L15 25 L80 25 L80 75 Q100 140 180 75 L225 75','Flow returns to zero before the next breath.'],['Incomplete expiration','M15 75 L15 25 L80 25 L80 75 Q110 140 200 95 L200 25 L225 25','The next breath starts while expiratory flow persists: consider air trapping.']].map(([t,d,a])=>`<div><h3>${t}</h3><svg viewBox="0 0 240 160" role="img" aria-label="${a}"><path d="M5 75H235" stroke="#92aeb7" stroke-dasharray="4"/><path d="${d}" fill="none" stroke="#128477" stroke-width="4"/><text x="175" y="65" fill="currentColor" font-size="12">zero flow</text></svg><p>${a}</p></div>`).join('')}</div></figure>`;
 const items=kind==='bmv'?[['Prepare','Call for help; position the airway and check bag, mask and oxygen.'],['Seal','Choose the mask and use a two-person seal when available.'],['Ventilate','Give breaths producing visible chest rise; avoid excessive pressure and rate.'],['Reassess','Check chest movement, heart rate and response. Correct ineffective ventilation.']]:kind==='devices'?[['Nasal prongs','Oxygen; variable FiO₂'],['Reservoir mask','Higher oxygen concentration; does not ventilate'],['HFNC / NIV','Selected support; monitor and plan failure'],['Bag-mask','Assisted breaths; assess chest rise']]:kind==='oxygenation'?[['Lungs','Load oxygen: saturation'],['Blood','Haemoglobin: carrying capacity'],['Circulation','Cardiac output: tissue delivery']]:[['Assess','What is failing?'],['Intervene','What should change?'],['Reassess','Continue, adjust or escalate?']];return `<figure class="visual-card"><figcaption><b>${kind==='bmv'?'Effective bag-mask ventilation: an observed skill':kind==='devices'?'Choose the job before the device':kind==='oxygenation'?'Three links in oxygen delivery':'Every intervention needs a response check'}</b><span>Conceptual learning diagram</span></figcaption><div class="flow-diagram">${items.map(([t,p],i)=>`<div><span class="map-number">0${i+1}</span><h3>${t}</h3><p>${p}</p></div>`).join('')}</div></figure>`;}
function closeDrawer(restore=true){drawerOpen=false;syncDrawer();if(restore)document.getElementById('menuBtn')?.focus();}
function syncDrawer(){const side=document.getElementById('sidebar');if(!side)return;const mobile=matchMedia('(max-width: 1050px)').matches;side.classList.toggle('open',mobile&&drawerOpen);side.inert=mobile&&!drawerOpen;side.setAttribute('aria-hidden',String(mobile&&!drawerOpen));document.getElementById('menuBtn').setAttribute('aria-expanded',String(mobile&&drawerOpen));document.getElementById('scrim').hidden=!(mobile&&drawerOpen);document.querySelector('main').inert=mobile&&drawerOpen;document.querySelector('.topbar').inert=mobile&&drawerOpen;document.body.classList.toggle('drawer-open',mobile&&drawerOpen);}
function bind(){
 for(const field of ['role','depth'])document.getElementById(field).onchange=e=>{state[field]=e.target.value;save();render(false);document.getElementById(field).focus();};
 document.getElementById('menuBtn').onclick=()=>{drawerOpen=true;syncDrawer();document.getElementById('closeMenu').focus();};document.getElementById('closeMenu').onclick=()=>closeDrawer();document.getElementById('scrim').onclick=()=>closeDrawer();
 document.querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>{state.checks[e.dataset.check]=e.checked;save();});
 document.querySelectorAll('[data-note]').forEach(e=>e.oninput=()=>{state.notes[e.dataset.note]=e.value;save();document.getElementById('note-status').textContent=storageOK?'Learning note saved in this browser.':'Session only: export before leaving.';});
 document.querySelector('[data-depth-all]')?.addEventListener('click',()=>{state.depth='nice';save();render();});
 document.querySelectorAll('[data-start]').forEach(e=>e.onclick=()=>{const u=byId(e.dataset.start);if(K.start(state,C,u)){save();go('assessment/'+u.id);}});
 document.querySelectorAll('[data-q] input[type=radio]').forEach(e=>e.onchange=()=>{const id=e.closest('[data-q]').dataset.q;(pending[id]||={}).choice=e.value;});
 document.querySelectorAll('[data-confidence]').forEach(e=>e.onchange=()=>{(pending[e.dataset.confidence]||={}).confidence=Number(e.value);});
 document.querySelectorAll('[data-submit]').forEach(e=>e.onclick=()=>{const id=e.dataset.submit,p=pending[id],context=e.dataset.context;if(!p?.choice||![1,2,3].includes(p.confidence)){document.getElementById('error-'+id).textContent='Choose an answer and rate confidence before submitting.';return;}if(context.startsWith('unit:')){if(!K.submit(state,C,byId(context.split(':')[1]),p.choice,p.confidence))return;}else{const pool=context==='baseline'?'baseline':'cases',q=[...C.baseline,...C.cases.flatMap(c=>c.steps)].find(q=>q.id===id);if(!q||state[pool][id])return;state[pool][id]={choice:p.choice,confidence:p.confidence,time:new Date().toISOString()};}save();render();document.querySelector('.feedback')?.scrollIntoView({block:'center'});});
 document.querySelectorAll('[data-next]').forEach(e=>e.onclick=()=>{const u=byId(e.dataset.next),step=K.advance(state,C,u);save();if(step==='finished')go('result/'+u.id);else render();});
 document.querySelectorAll('[data-case-retry]').forEach(e=>e.onclick=()=>{delete state.cases[e.dataset.caseRetry];delete pending[e.dataset.caseRetry];save();render();});
 document.querySelectorAll('[data-case-next]').forEach(e=>e.onclick=()=>{const q=C.cases.flatMap(c=>c.steps).find(q=>q.id===e.dataset.caseNext),r=state.cases[q.id];if(r?.choice===q.answer){r.acknowledged=true;save();render();}});
 document.getElementById('exportRecord')?.addEventListener('click',()=>download('OxyVent-learning-record.json',JSON.stringify({course:C.title,version:C.version,exported:new Date().toISOString(),record:state},null,2),'application/json'));
 document.getElementById('printRecord')?.addEventListener('click',()=>window.print());
 document.getElementById('resetRecord')?.addEventListener('click',()=>{if(confirm('Reset this edition’s learning record? Download it first to keep a copy.')){state=K.fresh();pending={};save();go('home');}});
}
function download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawerOpen)closeDrawer();if(e.key==='Tab'&&drawerOpen){const items=[...document.querySelectorAll('#sidebar a,#sidebar button,#sidebar select')].filter(e=>!e.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('hashchange',()=>{if(route()==='main'){document.getElementById('main').focus();return;}closeDrawer(false);render();});
matchMedia('(max-width: 1050px)').addEventListener('change',()=>{drawerOpen=false;syncDrawer();});
document.querySelector('.skip-link').onclick=e=>{e.preventDefault();const main=document.getElementById('main');main.focus();main.scrollIntoView({block:'start'});};
render(false);
