const units=[
 {title:"Welcome & baseline",time:"8 min",objective:"Understand the learning pathway and establish your baseline without affecting certification.",sections:[
  ["must","What this course certifies","This course develops recognition, interpretation and clinical decision-making. It does not by itself certify hands-on competence in bag-mask ventilation, NIV setup or intubation."],
  ["good","How mastery works","Units open sequentially. A score of 90% is required. If you miss an item, a focused explanation appears and you can try a parallel question."],
  ["nice","Choose your depth","Must Know material is compulsory. Good to Know and Nice to Know layers can be shown or hidden without losing your core progress."]],q:{stem:"Which outcome can be validly certified entirely online?",options:["Independent competence in pediatric intubation","Knowledge and clinical decision-making","Unsupervised NIV setup in every device"],answer:1,why:"Online assessment can demonstrate knowledge and clinical decision-making. Practical procedures require supervised simulation or workplace assessment."}},
 {title:"Recognise respiratory failure",time:"28 min",objective:"Differentiate respiratory distress from impending or established respiratory failure.",sections:[
  ["must","Distress is compensation","Tachypnoea, recession, nasal flaring and grunting show that the child is working to preserve gas exchange. Trend the child, not one isolated number."],
  ["must","Failure is loss of compensation","Reduced effort, altered consciousness, poor air entry, apnoea, cyanosis or bradycardia are late and dangerous signs. A falling respiratory rate can mean fatigue—not recovery."],
  ["good","Locate the problem","Stridor suggests upper-airway obstruction; wheeze suggests lower-airway narrowing; crackles and hypoxaemia suggest parenchymal disease. Mixed patterns are common."],
  ["nice","Physiological phenotypes","Respiratory failure may be predominantly hypoxaemic, hypercapnic or mixed. This distinction helps select support but must not delay stabilization."]],q:{stem:"A severely distressed child becomes quieter, drowsy and has poorer air entry. What is the safest interpretation?",options:["The child is settling","Respiratory muscle fatigue and impending failure","Oxygen has treated the underlying illness"],answer:1,why:"The apparent reduction in effort is a late warning sign. Escalate immediately while supporting airway and breathing."}},
 {title:"Oxygenation made simple",time:"32 min",objective:"Explain oxygenation, ventilation and the major mechanisms of hypoxaemia using bedside language.",sections:[
  ["must","Two different jobs","Oxygenation moves oxygen into blood. Ventilation removes carbon dioxide. A normal SpO₂ does not prove adequate ventilation."],
  ["must","Oxygen delivery needs more than SpO₂","Delivery to tissues depends on saturation, haemoglobin and cardiac output. A profoundly anaemic child can have a normal saturation but inadequate oxygen content."],
  ["good","Why oxygen sometimes fails","Low inspired oxygen, hypoventilation, V/Q mismatch and shunt cause hypoxaemia by different mechanisms. A large shunt may respond incompletely to additional oxygen."],
  ["nice","The dissociation curve","The flat upper portion provides a saturation reserve; on the steep portion, a small fall in PaO₂ can produce a rapid fall in SpO₂."]],q:{stem:"Which statement is correct?",options:["SpO₂ directly measures PaCO₂","Normal SpO₂ excludes respiratory failure","Ventilation may fail despite a normal SpO₂"],answer:2,why:"Oxygen saturation does not measure carbon-dioxide clearance. Clinical assessment and, when indicated, blood gas or CO₂ monitoring are needed."}},
 {title:"Pulse oximetry",time:"24 min",objective:"Obtain, validate and interpret pulse-oximeter readings safely.",sections:[
  ["must","Validate before acting","Check probe position, pulse agreement, signal quality and the child. Motion, cold extremities and poor perfusion can produce misleading values."],
  ["must","Treat the child","A concerning clinical picture overrides a reassuring or erratic number. Never delay airway or breathing support while trying multiple probes."],
  ["good","Know the limitations","Ambient light, nail products, skin pigmentation, dyshemoglobinaemia and venous pulsation may affect accuracy. Interpret trends and context."],
  ["nice","Beyond SpO₂","Waveform capnography and blood gases answer different questions. Select monitoring according to the physiological concern."]],q:{stem:"A shocked child has an SpO₂ of 74% with no stable waveform and a displayed pulse of 42 while the palpable pulse is 150. First action?",options:["Accept the saturation as accurate","Validate probe and signal while clinically supporting the child","Wait five minutes without intervention"],answer:1,why:"The pulse mismatch makes the reading unreliable, but the child still requires immediate clinical assessment and support."}},
 {title:"Conventional oxygen",time:"35 min",objective:"Select an appropriate oxygen source and interface, then monitor response and safety.",sections:[
  ["must","Choose by clinical need","Use an age-appropriate interface that delivers sufficient oxygen and is tolerated. Reassess saturation, effort, mental state and circulation after every change."],
  ["must","Escalate the child, not just the device","A rising oxygen requirement or worsening effort is treatment failure until proved otherwise. Call for help early."],
  ["good","Sources and interfaces","Know the capabilities and limitations of nasal prongs, simple masks, non-rebreathing masks, hoods, concentrators and cylinders available locally."],
  ["nice","Oxygen systems","Safe care also depends on supply estimation, cylinder security, fire safety, maintenance and contingency planning."]],q:{stem:"After changing an oxygen device, the best next step is to:",options:["Document it at the end of the shift","Reassess oxygenation, work of breathing and the child’s overall state","Wait for a blood gas before looking at the child"],answer:1,why:"Respiratory support is a monitored intervention. Response and deterioration must be identified promptly."}},
 {title:"Bag-mask ventilation",time:"32 min",objective:"Describe effective bag-mask ventilation and recognise ineffective or harmful technique.",sections:[
  ["must","The visible target","Position the airway, select the correct mask, create a seal and ventilate only enough to produce visible chest rise."],
  ["must","If the chest does not rise","Reposition, improve the seal, open the airway, suction when appropriate and use a two-person technique. Consider obstruction."],
  ["good","Avoid harm","Excessive pressure or rate causes gastric inflation, impaired venous return and lung injury. Coordinate compressions and ventilation according to current resuscitation guidance."],
  ["nice","Human factors","A designated airway lead, closed-loop communication and verbal confirmation of chest rise improve team performance."]],q:{stem:"The chest does not rise during bag-mask ventilation. What is the best immediate response?",options:["Squeeze harder without reassessment","Reposition the airway and improve mask seal","Increase oxygen flow only"],answer:1,why:"Correct airway position and an effective seal are the first troubleshooting steps; a two-person technique may help."}},
 {title:"High-flow nasal cannula",time:"38 min",objective:"Explain HFNC initiation, monitoring, weaning and failure recognition.",sections:[
  ["must","A monitored trial","HFNC provides heated, humidified high flow. It requires a defined indication, correctly sized interface, close reassessment and an escalation plan."],
  ["must","Failure must be recognised early","Persistent distress, worsening gas exchange, apnoea, altered sensorium or haemodynamic instability should prompt urgent escalation. HFNC must not delay intubation."],
  ["good","What to adjust","Flow mainly supports work of breathing and washout; FiO₂ is titrated to the oxygenation goal. Device-specific and local protocols govern exact settings."],
  ["nice","Weaning approaches","Some pathways reduce FiO₂ before flow; others use protocolised flow reductions. Consistency, monitoring and readiness criteria matter more than ritual."]],q:{stem:"A child on HFNC has increasing work of breathing and becomes drowsy. The priority is to:",options:["Continue unchanged for another two hours","Urgently assess for support failure and escalate","Reduce monitoring to let the child sleep"],answer:1,why:"Drowsiness with worsening effort suggests failure. Non-invasive support should never postpone definitive airway management."}},
 {title:"CPAP & non-invasive ventilation",time:"44 min",objective:"Select, monitor and troubleshoot CPAP/NIV while recognising contraindications and failure.",sections:[
  ["must","CPAP and bilevel support","CPAP provides continuous distending pressure. Bilevel NIV adds inspiratory pressure support and can assist ventilation and reduce work."],
  ["must","The child must be suitable","Ability to protect the airway, haemodynamic stability, manageable secretions, interface fit and close monitoring are fundamental. Immediate intubation needs are contraindications to delay."],
  ["good","Monitor the response","Assess effort, respiratory rate, heart rate, gas exchange, comfort, leak and synchrony. Define failure criteria before starting."],
  ["nice","Interface science","Oronasal, nasal and full-face interfaces have different leaks, dead space, pressure points and tolerability. Skin protection is part of respiratory care."]],q:{stem:"Which feature most strongly argues against persisting with NIV?",options:["The mask needs adjustment","Progressive obtundation with inability to protect the airway","Mild initial anxiety"],answer:1,why:"Loss of airway protection is a major failure signal and usually requires definitive airway management."}},
 {title:"Intubation preparation",time:"42 min",objective:"Prepare the child, team and equipment for safer pediatric intubation and post-intubation care.",sections:[
  ["must","Prepare physiology and equipment","Call skilled help, preoxygenate, anticipate hypotension, check suction and backup devices, calculate drugs carefully and assign roles."],
  ["must","Confirm and secure","Use waveform capnography when available, assess bilateral air entry and chest movement, note tube depth, secure the tube and reassess after movement."],
  ["good","The physiologically difficult airway","Severe hypoxaemia, shock, acidosis or raised intracranial pressure can make intubation dangerous even when laryngoscopy is technically easy."],
  ["nice","First-pass strategy","Optimised positioning, appropriate equipment, a clear primary and rescue plan, and a shared stop point reduce repeated attempts."]],q:{stem:"The most reliable immediate method listed for confirming tracheal placement is:",options:["Tube misting","Waveform capnography with clinical assessment","Improvement in skin colour alone"],answer:1,why:"Sustained waveform capnography, interpreted with clinical findings, is the preferred confirmation method when available."}},
 {title:"Invasive ventilation",time:"52 min",objective:"Interpret core ventilator variables and create a safe initial assessment plan.",sections:[
  ["must","Know the controls","FiO₂ and mean airway pressure influence oxygenation; minute ventilation influences CO₂ clearance. PEEP, tidal volume, rate and inspiratory time interact."],
  ["must","Reassess after connection","Look at the child, chest movement, exhaled tidal volume, pressures, saturation, CO₂, circulation and alarms. Confirm settings and tube position."],
  ["good","Resistance and compliance","Obstructive disease raises resistance and risks air trapping. Stiff lungs have reduced compliance and need a lung-protective strategy."],
  ["nice","Pressure versus volume targeting","Each has advantages and limitations. Understand what the ventilator guarantees, what varies and how leaks affect delivery."]],q:{stem:"Immediately after placing a child on a ventilator, which assessment is most appropriate?",options:["Review only the set tidal volume","Assess child, tube, delivered volumes, pressures, gas exchange and circulation","Silence all alarms until the blood gas returns"],answer:1,why:"Ventilator safety requires an integrated patient–airway–device assessment, not reliance on a single displayed setting."}},
 {title:"Sudden deterioration: DOPE",time:"36 min",objective:"Respond systematically when a ventilated child deteriorates.",sections:[
  ["must","DOPE","Consider Displacement, Obstruction, Pneumothorax and Equipment failure immediately while supporting oxygenation and ventilation."],
  ["must","The patient comes first","Call for help. If ventilator function or the circuit is uncertain, disconnect and provide appropriate manual ventilation while assessing resistance and chest rise."],
  ["good","Read the alarm in context","High pressure suggests resistance, obstruction, coughing, low compliance or pneumothorax. Low pressure suggests disconnection, leak or displacement."],
  ["nice","Waveform clues","Failure of expiratory flow to return to baseline suggests air trapping. Trends in pressure, volume and flow can identify problems before a crisis."]],q:{stem:"A ventilated child suddenly desaturates and the cause is unclear. Which framework is appropriate?",options:["FAST","DOPE","AMPLE only"],answer:1,why:"DOPE prompts immediate evaluation for displacement, obstruction, pneumothorax and equipment failure."}},
 {title:"Capstone & certificate",time:"25 min",objective:"Integrate recognition, escalation and troubleshooting across a deteriorating-child pathway.",sections:[
  ["must","Think in cycles","Assess → intervene → reassess. State what improvement should look like and how soon you expect it."],
  ["good","Escalation is a treatment","Calling skilled help, preparing equipment and arranging PICU transfer are active clinical interventions—not administrative afterthoughts."],
  ["nice","Continue learning","Online mastery is the gateway to supervised device stations, simulation and workplace assessment."]],q:{stem:"Which pattern best represents safe respiratory support?",options:["Choose a device and wait","Assess, intervene, define response, reassess and escalate if needed","Treat SpO₂ without evaluating the child"],answer:1,why:"Safe support is a continuous clinical cycle with predefined response and failure criteria."}}
];
const state=JSON.parse(localStorage.getItem('vikkypaedia-oxyvent-mastery-v2')||'{"done":[],"scores":{},"role":"ug","levels":["must","good","nice"]}');let current=-1,session=null;
const main=document.getElementById('main'),list=document.getElementById('unitList'),sidebar=document.getElementById('sidebar');
function save(){localStorage.setItem('vikkypaedia-oxyvent-mastery-v2',JSON.stringify(state));updateProgress()}
function updateProgress(){const n=state.done.length,p=Math.round(n/units.length*100),track=document.querySelector('.progress-track');document.getElementById('progressText').textContent=`${n} of ${units.length} units`;document.getElementById('progressFill').style.width=`${p}%`;if(track)track.setAttribute('aria-valuenow',n);renderNav()}
function closeSidebar(){sidebar.classList.remove('open');document.getElementById('menuBtn').setAttribute('aria-expanded','false')}
function openSidebar(){sidebar.classList.add('open');document.getElementById('menuBtn').setAttribute('aria-expanded','true')}
function renderNav(){list.innerHTML='';units.forEach((u,i)=>{if([0,6,9].includes(i)){const group=document.createElement('div');group.className='unit-group';group.textContent=i===0?'Foundations':i===6?'Respiratory support':'Advanced practice';list.appendChild(group)}let b=document.createElement('button');b.className='unit-btn '+(current===i?'active ':'')+(state.done.includes(i)?'done':'');b.disabled=i>0&&!state.done.includes(i-1);b.setAttribute('aria-current',current===i?'page':'false');b.innerHTML=`<span class="unit-num">${state.done.includes(i)?'✓':i+1}</span><span class="unit-copy"><span class="unit-title">${u.title}</span><small>${state.done.includes(i)?`Mastered · ${state.scores[i]}%`:b.disabled?'Locked':u.time}</small></span>`;b.onclick=()=>showUnit(i);list.appendChild(b)});const sb=document.createElement('button');sb.className='unit-btn certificate-nav '+(current===99?'active':'');sb.innerHTML='<span class="unit-num">✦</span><span class="unit-copy"><span class="unit-title">Certificate & evidence</span><small>Completion record</small></span>';sb.onclick=showCertificate;list.appendChild(sb)}
function showHome(){current=-1;closeSidebar();renderNav();const n=state.done.length,p=Math.round(n/units.length*100),complete=n===units.length,next=Math.min(n,units.length-1),cta=complete?'View my certificate':n?'Continue learning':'Start the course';main.innerHTML=`<div class="home-dashboard"><section class="welcome"><div class="welcome-copy"><div class="eyebrow">Mastery-based pediatric respiratory care</div><h1>See the child.<br>Support the breath.</h1><p>Build clinical confidence from oxygen assessment to non-invasive and invasive ventilation—one focused unit at a time.</p><button class="primary hero-cta" onclick="${complete?'showCertificate()':`showUnit(${next})`}">${cta} <span aria-hidden="true">→</span></button></div><div class="course-dial" style="--progress:${p*3.6}deg"><div><strong>${p}%</strong><span>course<br>mastered</span></div></div></section><div class="start-grid"><section class="panel depth-panel"><div class="panel-icon" aria-hidden="true">≋</div><div><h2>Choose your learning depth</h2><p>Must Know always stays on. Add deeper layers when you need them.</p><div class="level-pills">${[['must','Must Know'],['good','Good to Know'],['nice','Nice to Know']].map(x=>`<button class="pill ${state.levels.includes(x[0])?'on':''}" onclick="toggleLevel('${x[0]}')" aria-pressed="${state.levels.includes(x[0])}">${state.levels.includes(x[0])?'✓ ':''}${x[1]}</button>`).join('')}</div></div></section><section class="panel standard-panel"><div class="standard-score">9<span>/10</span></div><div><h2>Mastery in every unit</h2><p>No safety-critical errors. Focused remediation follows every missed concept.</p></div></section></div><section class="pathway-overview"><div class="pathway-head"><div><span class="eyebrow">Course map</span><h2>From recognition to respiratory support</h2></div><span>${n} of ${units.length} mastered</span></div><div class="phase-grid">${[{name:'Foundations',range:'Units 1–6',count:Math.min(n,6),total:6},{name:'Respiratory support',range:'Units 7–9',count:Math.max(0,Math.min(n-6,3)),total:3},{name:'Advanced practice',range:'Units 10–12',count:Math.max(0,n-9),total:3}].map((x,i)=>`<button class="phase-card" onclick="showUnit(${i===0?0:i===1?6:9})" ${i>0&&n<(i===1?6:9)?'disabled':''}><span class="phase-number">0${i+1}</span><span><strong>${x.name}</strong><small>${x.range}</small></span><span class="phase-progress">${x.count}/${x.total}</span></button>`).join('')}</div></section></div>`}
function toggleLevel(l){if(l==='must')return;state.levels=state.levels.includes(l)?state.levels.filter(x=>x!==l):[...state.levels,l];save();current<0?showHome():showUnit(current)}
function showUnit(i){current=i;session=null;closeSidebar();renderNav();const u=units[i],phase=i<6?'Foundations':i<9?'Respiratory support':'Advanced practice';main.innerHTML=`<article class="lesson"><header class="lesson-head"><div><div class="eyebrow">Unit ${i+1} · ${phase}</div><h1>${u.title}</h1></div><span class="time"><span aria-hidden="true">◷</span> ${u.time}</span></header><div class="objective-block"><span>Learning outcome</span><p class="objective">${u.objective}</p></div><div class="lesson-sections">${u.sections.filter(s=>state.levels.includes(s[0])).map((s,n)=>`<section class="content-card lesson-card level-${s[0]}"><div class="card-top"><span class="level ${s[0]}">${s[0]} to know</span><span class="card-index">${String(n+1).padStart(2,'0')}</span></div><h2>${s[1]}</h2><p>${s[2]}</p></section>`).join('')}</div><section class="content-card assessment-intro"><div class="assessment-intro-grid"><div><span class="level must">Unit assessment</span><h2>Prove your understanding</h2><p>Ten questions test factual recall and bedside interpretation against this unit’s learning outcomes.</p><div class="assessment-rules"><span>10 questions</span><span>9/10 to pass</span><span>No critical miss</span></div><button class="primary" onclick="beginAssessment(${i})">${state.done.includes(i)?'Reattempt assessment':'Start assessment'} <span aria-hidden="true">→</span></button></div><div class="assessment-number" aria-hidden="true">10<small>items</small></div></div></section><div class="footer-actions"><span class="mastery">${state.done.includes(i)?'✓ Mastered · '+state.scores[i]+'%':'Pass this assessment to unlock the next unit'}</span><button class="secondary" onclick="showHome()">Course home</button></div></article>`;window.scrollTo({top:0,behavior:'smooth'})}
function beginAssessment(i){const order=assessmentBanks[i].map((_,n)=>n);for(let n=order.length-1;n>0;n--){const j=Math.floor(Math.random()*(n+1));[order[n],order[j]]=[order[j],order[n]]}session={unit:i,order,pos:0,correct:0,criticalMiss:false,missed:[]};renderAssessment()}
function renderAssessment(){const i=session.unit,item=assessmentBanks[i][session.order[session.pos]],u=units[i];main.innerHTML=`<article class="lesson assessment-page"><header class="assessment-top"><div><div class="eyebrow">Unit ${i+1} · knowledge check</div><h1>${u.title}</h1></div><strong>Question ${session.pos+1} of 10</strong></header><div class="quiz-progress" role="progressbar" aria-label="Assessment progress" aria-valuemin="1" aria-valuemax="10" aria-valuenow="${session.pos+1}"><span style="width:${(session.pos+1)*10}%"></span></div><section class="content-card scenario"><div class="question-meta"><span>Learning outcome · ${item.slo}</span>${item.critical?'<span class="critical-tag">Safety-critical</span>':''}</div><h2>${item.stem}</h2><div class="options">${item.options.map((o,j)=>`<button type="button" class="option" onclick="selectAssessmentAnswer(${j},this)"><b>${String.fromCharCode(65+j)}</b><span>${o}</span></button>`).join('')}</div><div class="feedback" id="feedback" aria-live="polite"></div></section><p class="assessment-note">Your answer is final for this attempt. Feedback appears immediately.</p></article>`;window.scrollTo({top:0,behavior:'smooth'})}
function selectAssessmentAnswer(choice,el){const item=assessmentBanks[session.unit][session.order[session.pos]],ok=choice===item.answer,f=document.getElementById('feedback');document.querySelectorAll('.option').forEach((x,j)=>{x.disabled=true;if(j===item.answer)x.classList.add('correct')});el.classList.add(ok?'correct':'incorrect');if(ok)session.correct++;else{session.missed.push(item.slo);if(item.critical)session.criticalMiss=true}f.className='feedback show '+(ok?'':'wrong');f.innerHTML=`<strong>${ok?'Correct.':'Incorrect.'}</strong> ${item.why}${!ok?`<div class="remediation"><b>Remediation target:</b> ${item.slo}</div>`:''}<div class="feedback-action"><button class="primary" onclick="nextAssessmentQuestion()">${session.pos===9?'See result':'Next question'} →</button></div>`}
function nextAssessmentQuestion(){session.pos++;session.pos<10?renderAssessment():finishAssessment()}
function finishAssessment(){const i=session.unit,score=session.correct*10,passed=score>=90&&!session.criticalMiss;state.scores[i]=Math.max(state.scores[i]||0,score);if(passed&&!state.done.includes(i))state.done.push(i);save();const missed=[...new Set(session.missed)];main.innerHTML=`<article class="lesson"><section class="content-card result-card ${passed?'passed':'needs-work'}"><div class="score-ring"><strong>${score}%</strong><span>${session.correct}/10</span></div><div><div class="eyebrow">${passed?'Unit mastered':'Remediation required'}</div><h1>${passed?'Strong work.':'Not yet—review and retry.'}</h1><p>${passed?'You met the 90% standard without a safety-critical error.':session.criticalMiss?'A safety-critical item was missed. Review the targeted outcome before reassessment.':'You need at least 9 correct answers to demonstrate mastery.'}</p></div></section>${missed.length?`<section class="content-card"><h2>Your focused remediation</h2><p>Review these specific learning outcomes before attempting a new set:</p><div class="remediation-list">${missed.map(x=>`<span>${x}</span>`).join('')}</div></section>`:''}<div class="footer-actions"><button class="secondary" onclick="showUnit(${i})">Review unit</button>${passed?`<button class="primary" onclick="${i===units.length-1?'showCertificate()':`showUnit(${i+1})`}">${i===units.length-1?'View certificate':'Open next unit'} →</button>`:`<button class="primary" onclick="beginAssessment(${i})">Retry 10-question assessment →</button>`}</div></article>`;window.scrollTo({top:0,behavior:'smooth'})}
function showCertificate(){current=99;renderNav();closeSidebar();const eligible=state.done.length===units.length;main.innerHTML=`<section class="lesson certificate-page"><div class="eyebrow">Completion record</div><h1>Certificate & evidence</h1>${eligible?`<div class="certificate"><div class="certificate-seal" aria-hidden="true">O<sub>2</sub></div><div class="eyebrow">Certificate of mastery</div><h1>Vikkypaedia OxyVent Module</h1><p>This certifies that</p><div class="name" contenteditable="true" role="textbox" aria-label="Enter learner name">Learner name</div><p>completed the pediatric oxygenation and ventilation knowledge and clinical decision-making pathway<br>having achieved the required <strong>90% mastery standard in every unit</strong>.</p><div class="certificate-meta"><span>12 units mastered</span><span>120 assessment items</span><span>Knowledge & decision-making</span></div><p><small>This online certificate does not replace supervised procedural competency assessment.</small></p><button class="primary" onclick="window.print()">Print certificate</button></div>`:`<div class="content-card cert-lock"><div class="lock-mark" aria-hidden="true">${state.done.length}/${units.length}</div><h2>Your certificate is taking shape</h2><p>Master every unit at 90% or above, without a safety-critical miss, to unlock it.</p><button class="primary" onclick="showUnit(${Math.min(state.done.length,units.length-1)})">Continue learning <span aria-hidden="true">→</span></button></div>`}<section class="content-card source-list"><span class="level good">Evidence library</span><h2>Core clinical sources</h2><p>Course content is grounded in international pediatric respiratory guidance and must be adapted to local protocols.</p><ul><li><a href="https://www.who.int/publications/i/item/9789241549554" target="_blank" rel="noopener">WHO — Oxygen therapy for children</a></li><li><a href="https://www.who.int/publications/i/item/9789241510219" target="_blank" rel="noopener">WHO — Paediatric emergency triage, assessment and treatment</a></li><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9848214/" target="_blank" rel="noopener">PALICC-2 — Pediatric acute respiratory distress syndrome</a></li><li><a href="https://www.aarc.org/resource/clinical-practice-guidelines/" target="_blank" rel="noopener">AARC — Clinical practice guidelines</a></li><li><a href="https://www.who.int/publications/i/item/9789241516914" target="_blank" rel="noopener">WHO/UNICEF — Oxygen therapy devices</a></li></ul><div class="callout"><strong>Clinical governance:</strong> Thresholds, device settings and drug guidance must be reviewed against current national, institutional and manufacturer protocols before institutional release.</div></section></section>`;window.scrollTo({top:0,behavior:'smooth'})}
document.getElementById('roleSelect').value=state.role;document.getElementById('roleSelect').onchange=e=>{state.role=e.target.value;save()};document.getElementById('menuBtn').onclick=()=>sidebar.classList.contains('open')?closeSidebar():openSidebar();document.getElementById('sidebarClose').onclick=closeSidebar;document.getElementById('sidebarScrim').onclick=closeSidebar;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar()});window.showUnit=showUnit;window.showHome=showHome;window.toggleLevel=toggleLevel;window.beginAssessment=beginAssessment;window.selectAssessmentAnswer=selectAssessmentAnswer;window.nextAssessmentQuestion=nextAssessmentQuestion;window.showCertificate=showCertificate;showHome();updateProgress();
