import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { course } from './content/course.mjs';
const root = path.dirname(fileURLToPath(import.meta.url));
export function validate(c, fixture = false) {
  const fail = s => { throw Error(s); }, ids = new Set(), sources = new Set(c.sources.map(s => s.id));
  const unique = id => { if (!id || ids.has(id)) fail(`Duplicate/missing ID: ${id}`); ids.add(id); };
  const refs = entity => { if (!entity.sourceIds?.length || entity.sourceIds.some(id => !sources.has(id))) fail(`Missing source on ${entity.id}`); };
  function question(q) { unique(q.id); refs(q); if (q.options.length !== 4 || new Set(q.options.map(o => o.id)).size !== 4 || !q.options.some(o => o.id === q.answer) || q.options.some(o => !o.text || !o.feedback)) fail(`Invalid options: ${q.id}`); }
  if (!fixture && c.units.length !== 12) fail('Expected twelve units');
  for (const u of c.units) {
    unique(u.id); if (u.outcomes.length < 3 || u.outcomes.length > 5 || u.sections.length < 4 || u.questions.length !== 10) fail(`Unit contract: ${u.id}`);
    if (Object.keys(c.roles).some(r => !u.roleNotes[r])) fail(`Role coverage: ${u.id}`);
    for (const s of u.sections) { unique(s.id); refs(s); if (!['must','good','nice'].includes(s.depth)) fail(`Bad depth ${s.id}`); }
    for (const form of ['a','b']) { const positions = [0,0,0,0]; for (const p of u.questions) { const q=p.variants.find(q=>q.form===form); if (!q) fail(`Missing variant ${p.id}`); positions[q.options.findIndex(o=>o.id===q.answer)]++; } if (Math.max(...positions)-Math.min(...positions)>1) fail(`Answer balance ${u.id}/${form}`); }
    for (const p of u.questions) { unique(p.id); if (p.variants.length !== 2 || p.variants[0].stem === p.variants[1].stem) fail(`Parallel variants: ${p.id}`); if (!u.sections.some(s=>s.id===p.sectionId&&s.depth==='must')) fail(`Hidden prerequisite: ${p.id}`); p.variants.forEach(question); }
  }
  c.baseline.forEach(question); c.cases.forEach(c=>{ unique(c.id); c.steps.forEach(question); });
  return { units:c.units.length, sections:c.units.reduce((n,u)=>n+u.sections.length,0), assessmentItems:c.units.length*20, baseline:c.baseline.length, caseDecisions:c.cases.reduce((n,c)=>n+c.steps.length,0), sources:c.sources.length };
}
const counts = validate(course, process.argv.includes('--fixture'));
const data = `/* Generated by node build.mjs; edit content/*.mjs. */\nwindow.COURSE = ${JSON.stringify(course, null, 2)};\n`;
const shell = fs.readFileSync(path.join(root,'shell.html'),'utf8').replaceAll('{{VERSION}}',course.version);
const css = fs.readFileSync(path.join(root,'styles.css'),'utf8');
const core = fs.readFileSync(path.join(root,'core.js'),'utf8');
const app = fs.readFileSync(path.join(root,'app.js'),'utf8');
for (const [name, text] of [['data.js',data],['core.js',core],['app.js',app]]) new vm.Script(text,{filename:name});
fs.writeFileSync(path.join(root,'data.js'),data); fs.writeFileSync(path.join(root,'index.html'),shell);
const safeScript = s => s.replace(/<\/script/gi,'<\\/script');
const offline = shell.replace(/<link rel="stylesheet"[^>]+>/,'<style>'+css+'</style>').replace(/<script src="data.js[^>]+><\/script>/,'<script>'+safeScript(data)+'</script>').replace(/<script src="core.js[^>]+><\/script>/,'<script>'+safeScript(core)+'</script>').replace(/<script src="app.js[^>]+><\/script>/,'<script>'+safeScript(app)+'</script>').replace(/<link rel="icon"[^>]+>/,'');
fs.writeFileSync(path.join(root,'offline.html'),offline);
fs.writeFileSync(path.join(root,'build-report.json'),JSON.stringify({version:course.version,counts,validation:'passed',offline:'Generated from exact current shell, styles, data and engine'},null,2));
console.log(JSON.stringify({version:course.version,...counts,validation:'passed'}));
