import {section as s,decisions,single} from './helpers.mjs';
export const capstone={id:'capstone',title:'Follow the deteriorating child',subtitle:'Integrate assessment, escalation, airway support and transfer across an unfolding case.',minutes:24,phase:'Advanced practice',visual:'cycle',sequential:true,outcomes:['Prioritize actions as new observations emerge.','Reassess response and recognize when support has failed.','Communicate a safe post-intubation and transfer plan.'],roleNotes:{ug:'Explain the mechanism and next supervised action at each stage; avoid naming a device without stating its purpose.',nurse:'Identify and communicate deterioration, check delivery and prepare the requested rescue support within your role.',picu:'Track the patient–airway–device relationship as the case progresses; state which change requires immediate review.',pg:'Lead escalation decisions with explicit failure criteria, physiological preparation and an actionable handover.'},sections:[
s('capstone-assess','Commit to the problem before the device',['Each form follows an original fictional patient. You will see one stage at a time. Assess effort, air entry, alertness, perfusion and the reliability of measurements before deciding what the next action should accomplish.','You are selecting the safest team response, not claiming personal authority to perform every action. Use the responsibility lens for your role. A diagnosis or a single saturation should not substitute for identifying the immediate physiological threat.'],[],'must',['aha-bls','aha-als','course']),
s('capstone-plan','Carry a response plan forward',['Oxygen needs a target, delivery plan and reassessment. A monitored non-invasive trial needs a suitable child, trained observation and a failure action. Improvement should appear in the child’s state as well as the monitor.','The case’s oxygen target is explicitly supplied as a fictional local prescription. Do not generalize it to every diagnosis. When the case supplies a weight-based example, calculate it and check the named protocol and device limits.'],[],'must',['rch-oxygen','rch-hfnc','course']),
s('capstone-escalate','Change course when the evidence changes',['Drowsiness, recurrent apnoea, worsening gas exchange or circulatory instability can make continued non-invasive support unsafe. Escalate immediately rather than waiting for a planned trial endpoint.','A case may move on after an incorrect answer so you can complete the assessment. The next stage describes the actions of the fictional clinical team, not an endorsement of your earlier choice. Review the explanation and your final remediation targets.'],[],'must',['aha-als','course']),
s('capstone-airway','Think beyond tube insertion',['Prepare physiology and an airway/rescue team. Confirm placement with CO₂ evidence and clinical assessment, check depth, secure the tube and evaluate delivered ventilation and circulation.','After movement or sudden deterioration, assess DOPE causes while providing support. A CO₂ waveform does not rule out a mainstem tube. A low-pressure alarm after a loose connection points toward a delivery problem, but the child remains the priority.'],[],'must',['aha-als','palicc']),
s('capstone-transfer','A safe plan must survive handover',['A transfer plan includes the current clinical trend, support and response, source/power sufficiency, monitoring, escort, backup and an accepting team. Do not let departure timing force a reduction below support the child needs.','At the end, explain one finding that changed your decision and one tempting alternative you rejected. Use the first-attempt record to distinguish reasoning before feedback from later correction.'],[],'must',['rch-oxygen','rch-hfnc','course']),
s('capstone-depth','Debrief the decisions as a sequence',['Compare the earliest warning with the moment the team escalated. Was there an earlier opportunity to recognize failure or prepare resources? A good debrief asks which information changed the plan and what the team should do differently next time.'],[],'good',['course']),
s('capstone-enrich','Take the learning to supervised practice',['Bring a case summary and the BMV checklist to a supervised simulation session. Ask the assessor to observe communication, response checks and practical technique, not only your verbal explanation.'],[],'nice',['course'])],reflection:'Which observation changed your plan most? Explain the action you took, the alternative you rejected and what you expected to improve.'};
capstone.questions=decisions(capstone,[
['assess','Stage 1 · Asha, 18 months, 9 kg, arrives at a district hospital with pneumonia. She is alert, RR 56/min, marked recession and SpO₂ 86% with a good signal. What is the immediate team priority?','Stage 1 · Kabir, 7 months, 7 kg, arrives with bronchiolitis, marked recession and reliable SpO₂ 87%. He is alert but tiring. What is the immediate team priority?','Support oxygenation and assess breathing/circulation with early skilled review~Both patients need prompt support and whole-child assessment.','Wait for radiology before starting respiratory support~The clinical oxygenation problem is already actionable.','Select intubation solely from saturation without further assessment~Severity and effective breathing must be integrated.','Treat the reading as artifact despite good signal and matching clinical findings~There is no basis to dismiss the concern.','Start stabilization while defining the physiological problem.',true],
['plan','Stage 2 · Asha’s fictional local prescription targets SpO₂ 92–96%. Which plan is complete?','Stage 2 · Kabir’s treating clinician supplies an individualized 92–96% target for this exercise. Which plan is complete?','Specify target, interface/flow, response check and escalation action~A usable plan connects delivery to clinical goals.','Specify the saturation range alone~That leaves delivery and response actions unclear.','Use the highest oxygen flow regardless of device~Flow must suit the system and clinical response.','Assume the exercise target applies to all bronchiolitis patients~Targets and initiation thresholds need their clinical context.','The supplied case target is not a universal guideline.'],
['assess','Stage 3 · Asha’s saturation display becomes erratic during crying and the pulse disagrees with the clinical pulse. What now?','Stage 3 · Kabir has cold extremities; the monitor pulse is 50/min while his clinical pulse is 160/min. How should the team respond?','Continue clinical support while validating probe, signal and perfusion~The measurement is questionable but the child still needs care.','Stop all support until the reading is accurate~Measurement checks must not delay treatment.','Treat the displayed pulse as proven severe bradycardia~Clinical confirmation is needed.','Ignore the child’s respiratory signs because the monitor is unreliable~Unreliable data do not make the child well.','Work on patient support and measurement quality together.',true],
['plan','Stage 4 · The team selects a monitored HFNC trial for Asha, still alert with preserved circulation. Using the RCH example of 2 L/kg/min at 9 kg, what follows?','Stage 4 · Kabir is selected for a monitored HFNC trial. Using the RCH example of 2 L/kg/min at 7 kg, what follows?','Calculate weight × 2 and verify the local/device plan~The examples give 18 L/min for Asha and 14 L/min for Kabir; the named protocol is not universal.','Use 2 L/min for either child~This omits the weight multiplier.','Use the adult maximum for both infants~The maximum is not a weight-based starting prescription.','Increase ordinary prong flow without a high-flow system~HFNC requires its designed system.','Apply the specified example correctly and retain the monitoring/failure plan.'],
['plan','Stage 5 · Asha’s early HFNC response is RR 44/min, less recession and better interaction with falling FiO₂. What is the best interpretation?','Stage 5 · Kabir becomes more interactive, his effort falls and oxygen requirement decreases. What does this suggest?','A favorable trajectory that still requires planned monitoring~Several clinical domains improve together.','Guaranteed success for the remainder of admission~Later deterioration remains possible.','A reason to stop every observation immediately~Support continues to require monitoring.','An indication to intubate solely because HFNC was used~Device use alone does not mandate escalation.','Continue the agreed trial with explicit response checks.'],
['escalate','Stage 6 · Later, Asha becomes drowsy with recurrent apnoea despite SpO₂ 95% on oxygen. What now?','Stage 6 · Kabir develops recurrent apnoea and worsening responsiveness while SpO₂ remains 96%. What is the priority?','Recognize support failure and urgently escalate airway/ventilation care~Normal saturation on oxygen cannot exclude failing ventilation.','Keep the trial unchanged until its scheduled endpoint~Apnoea and altered consciousness require immediate action.','Reduce monitoring so the child can sleep~This risks missing further deterioration.','Treat saturation alone as proof of recovery~The clinical evidence contradicts it.','Clinical failure overrides a reassuring saturation.',true],
['airway','Stage 7 · The team prepares intubation for Asha, who is now poorly perfused. Which preparation is strongest?','Stage 7 · Kabir needs definitive support and is at risk of desaturation during airway management. What should be ready?','Experienced help, physiological preparation, suction, monitoring and rescue plan~Prepare the child and the entire team/system.','Only the correct tube size~That does not address physiological or rescue risks.','Repeated attempts without agreed stop points~This increases the risk of accumulating harm.','A plan to check drugs after administration~Medication checking must happen before use.','An airway plan must protect physiology as well as achieve placement.',true],
['airway','Stage 8 · Asha has sustained exhaled CO₂ after intubation. What still needs checking?','Stage 8 · Kabir has a CO₂ waveform after tube placement. What completes the immediate assessment?','Tube depth, bilateral air entry, fixation, delivered ventilation and circulation~A waveform does not establish depth or the entire clinical response.','Nothing further until the next blood gas~Immediate bedside checks remain essential.','Only tube misting~Misting is weaker evidence and does not add the missing checks.','Only the device’s mode label~That does not verify the patient’s support.','Confirm placement and ongoing effective support.',true],
['airway','Stage 9 · After Asha is moved, a low-pressure alarm appears and a circuit connection is loose. What should happen?','Stage 9 · After Kabir is repositioned, delivered volume falls and a circuit limb has disconnected. What is the priority?','Support the child and correct/check the delivery system promptly~Treat a likely equipment cause while reassessing airway and physiology.','Silence the alarm and wait for radiology~A visible delivery failure needs immediate attention.','Assume worsening lung compliance is the only cause~The low-pressure and disconnection clues matter.','Increase set pressure before checking the connection~This does not correct a disconnected gas path.','Use the observed cause without losing the whole-child assessment.',true],
['transfer','Stage 10 · Asha is stabilized for PICU transfer. Which handover is complete?','Stage 10 · Kabir is ready for supported transfer to a receiving team. What must the handover include?','Trend, airway/support, response, gas/power reserve, escort and rescue plan~The receiving and transport teams can continue safe support.','Diagnosis and bed allocation alone~Current support and contingencies are missing.','A previous stable saturation without device settings~The support dependency is hidden.','Departure time without transport capability~Timing does not establish safe transport.','The endpoint is a supported child and an actionable handover.',true]]);

const q=(id,stem,opts,why,refs,critical=false)=>single(id,stem,opts.map(o=>o.split('~')),why,refs,critical);
export const baseline=[
q('base-vent','A child on oxygen has SpO₂ 97%, shallow breaths and worsening drowsiness. What matters most?',['Assess ventilation and arrange urgent support~A saturation can stay high despite inadequate ventilation.','Reduce observation because saturation is normal~Clinical deterioration is more concerning than the number.','Increase oxygen as the only response~Oxygen does not restore effective breathing.','Wait for cyanosis before escalation~This is a late and potentially masked sign.'],'Oxygenation and ventilation are different functions.',['aha-bls','aha-als'],true),
q('base-trend','A distressed child’s respiratory rate falls while air entry and interaction improve. Which interpretation best fits?',['Improvement is supported by the accompanying clinical changes~The rate trend agrees with more effective, comfortable breathing.','Any falling rate proves fatigue~The associated findings distinguish recovery from failure.','Saturation alone is still the only relevant measure~The whole-child trend matters.','The child no longer needs any reassessment~A favorable response still needs monitoring.'],'Read observations together.',['aha-bls']),
q('base-oxygen','Two children both have SpO₂ 98%, but one has severe anaemia and poor perfusion. Which statement fits?',['Equal saturation does not mean equal tissue oxygen delivery~Carrier quantity and blood flow also matter.','Equal saturation proves equal arterial oxygen content~Haemoglobin concentration contributes strongly to content.','Oximetry directly measures cardiac output~It does not measure systemic flow.','The anaemic child’s reading must be false~It can be accurate and still incomplete.'],'Saturation, content and delivery are distinct.',['aha-als','palicc'])];

export const cases=[{id:'power',title:'The power fails during referral',setting:'District hospital · oxygen continuity',intro:'A fictional infant needs oxygen during referral. Work through the supply problem and the handover.',sourceIds:['rch-oxygen','course'],debrief:'A source check is clinical work. A stable value before transfer does not guarantee support during a power or gas failure. The safe plan connects the patient, equipment, escort and receiving team.',steps:[
q('case-power-1','The concentrator stops during a power failure. The child still needs oxygen. What is the immediate response?',['Provide an appropriate backup while assessing the child~Maintain needed support and confirm the backup functions.','Wait for the electrician before acting~Respiratory support cannot depend on repair timing.','Keep the disconnected tubing in place~An interface without supply does not deliver therapy.','Use the last saturation as proof of safety~The clinical situation has changed.'],'Maintain support while addressing the source failure.',['rch-oxygen'],true),
q('case-power-2','The backup cylinder has 120 usable L at a total draw of 6 L/min. The journey may take 40 minutes. What follows?',['The theoretical 20 minutes is insufficient; arrange adequate supply/reserve~Even the simple arithmetic is shorter than the journey.','The cylinder is adequate because it is labelled oxygen~Content and duration matter.','A 20-minute supply always covers a 40-minute journey~It does not match the stated consumption.','Reduce support solely to make the cylinder last~Support must meet the child’s needs.'],'Use actual consumption and reserve when planning transport.',['course','rch-oxygen'],true),
q('case-power-3','Supply is secured. What should the transport handover now include?',['Clinical trend, support, response, monitoring and rescue arrangements~This makes the plan executable by the next team.','The cylinder serial number only~It omits the patient’s support needs.','Only the original diagnosis~Current physiology matters.','Only the expected arrival time~This does not describe safe care en route.'],'Transport is a continuation of treatment.',['rch-oxygen'])]},
{id:'silent',title:'The wheeze becomes quiet',setting:'Emergency department · recognition',intro:'A fictional 5-year-old with severe wheeze becomes less noisy. Decide whether the trajectory is reassuring.',sourceIds:['aha-bls','aha-als'],debrief:'Quietness can reflect recovery or very poor airflow. Effective breathing, alertness and circulation distinguish the two. A falling rate plus exhaustion is not a reason to reduce observation.',steps:[
q('case-silent-1','RR falls from 50 to 26, but air entry decreases and the child becomes drowsy. What is the concern?',['Loss of compensation~The associated signs indicate fatigue and failing airflow.','Recovery proven by a lower rate~The other domains are worsening.','Ordinary sleep without respiratory risk~The context makes that assumption unsafe.','A monitor setting issue alone~The clinical examination is concerning.'],'Interpret the trend across several domains.',['aha-bls','aha-als'],true),
q('case-silent-2','SpO₂ is 96% on oxygen. Does this change the urgency?',['No; urgently assess ventilation and support needs~Oxygen can conceal inadequate ventilation on SpO₂.','Yes; it excludes respiratory failure~SpO₂ does not measure CO₂ clearance.','Yes; the child can wait for routine review~The deterioration is already clinically evident.','Only cyanosis can justify escalation~Cyanosis is not required.'],'Act on the child, not saturation alone.',['aha-bls','aha-als'],true),
q('case-silent-3','Skilled help arrives. Which statement best transfers your concern?',['Earlier distress, now poor air entry/drowsiness, current support and actions~This gives the team a usable trajectory.','The child is quieter~That phrase could be mistaken for improvement.','The saturation is normal~It hides oxygen use and ventilation concern.','Asthma is the diagnosis~The label does not state urgency.'],'Describe what changed and what support is needed.',['aha-als'])]},
{id:'movement',title:'An alarm after repositioning',setting:'PICU · patient–airway–device',intro:'A fictional intubated child deteriorates immediately after being moved. Work through the urgent checks.',sourceIds:['aha-als','palicc'],debrief:'Repositioning can change depth and circuit connections. Capnography helps confirm exhaled CO₂, but does not guarantee correct tube depth. Recheck effective support after each correction.',steps:[
q('case-move-1','SpO₂ falls and chest movement is poor. What is the first priority?',['Call help and support the child while checking DOPE causes~Assessment and stabilization must occur together.','Wait for a chest film before support~Immediate deterioration needs immediate action.','Assume the monitor is false because the move was brief~A short movement can still affect airway/circuit.','Silence alarms to complete repositioning~That removes warning without treating the cause.'],'Start with the patient and reversible causes.',['aha-als'],true),
q('case-move-2','The tube mark is deeper and left air entry is reduced, but CO₂ persists. What should be considered?',['Mainstem migration among urgent causes~CO₂ can remain present with a tube too deep.','A waveform guarantees correct depth~It does not.','Only an oxygen-source failure~That does not explain the changed depth.','Resolved lung disease~That does not fit sudden asymmetry.'],'Check placement, depth and bilateral ventilation separately.',['aha-als'],true),
q('case-move-3','The skilled team corrects the airway problem. What follows?',['Reassess child, fixation, depth, delivered ventilation and circulation~Confirm that the correction produced a safe response.','Return immediately to the previous observation interval without checking~The response must be verified first.','Document only the tube mark~Record the clinical change and response as well.','Remove alarms because the cause was found~Ongoing support still needs monitoring.'],'Every correction needs an observed response.',['aha-als','palicc'])]}];
