import {section as s,decisions} from './helpers.mjs';
export const oxygen={id:'oxygen',title:'Prescribe and reassess oxygen',subtitle:'Choose a delivery system, state the target, and prove that the child is improving.',minutes:20,phase:'Foundations',visual:'devices',
outcomes:['Write an oxygen plan with a target and reassessment point.','Match an interface to the child and available equipment.','Recognize delivery failure and clinical deterioration.'],
roleNotes:{ug:'Explain why flow and inspired oxygen concentration differ. Present your proposed plan to a supervisor.',nurse:'Check the prescribed target, source, tubing and interface. Document response and escalate rising support needs.',picu:'Track oxygen exposure, delivery performance and gas supply during transfer; identify when oxygen alone is inadequate.',pg:'Choose a condition-specific target, justify the support plan and agree escalation/transfer arrangements with the team.'},
sections:[
s('oxygen-plan','Write a treatment plan, not just a flow',['“Give oxygen” leaves essential decisions open. Record the indication, target saturation, source/interface, starting flow or FiO₂, reassessment and escalation plan. Flow is gas volume per minute; FiO₂ is oxygen fraction. They are not interchangeable.','In this fictional ward exercise, the supervising clinician prescribes a target of 92–96% and reassessment immediately after changing support. This is the supplied case prescription, not a universal target. Check effort, air entry, alertness and perfusion alongside SpO₂.'],['Document what improvement should look like and who will respond if it does not occur.'],'must',['rch-oxygen','course']),
s('oxygen-target','A number needs a clinical context',['Separate an initiation threshold from a treatment target. In NICE bronchiolitis guidance, give oxygen for persistent SpO₂ below 90% at age six weeks or older, or below 92% in younger infants or children with underlying conditions. A specialist cardiac plan may need further individualization.','Do not transplant those thresholds to resuscitation, shock or PARDS. An apnoeic or exhausted child needs airway and breathing support; a cutoff calculation must not delay it.'],[],'must',['nice','aha-bls']),
s('oxygen-device','Choose the system for the job',['Nasal prongs are often tolerated well but deliver variable FiO₂ because room air is entrained. A simple mask also has variable performance and needs enough fresh gas to clear exhaled gas. A reservoir mask can provide higher oxygen concentration with adequate flow, fit and an inflated reservoir; it does not ventilate an apnoeic child.','Venturi adapters create a specified mixture through air entrainment. Keep ports clear and use the printed flow. A higher flow through ordinary prongs does not create a heated, humidified HFNC system.'],['Minimum mask flow is device-specific: RCH describes 4 L/min for its masks; other masks may specify 5 L/min or more. Check the actual manufacturer instructions.','A reservoir collapsing completely during inspiration prompts a supply/flow/fit check.'],'must',['rch-oxygen']),
s('oxygen-response','Worked example: better SpO₂, worse breathing',['An 18-month-old with pneumonia arrives at a district hospital: SpO₂ 87% with a good signal, marked recession and initially good effort. Oxygen is started under the local plan. Five minutes later SpO₂ is 94%, but the child is drowsy and air entry is poorer.','The saturation target has been reached; the child is deteriorating. Call skilled help, reassess airway and ventilation and prepare appropriate support. Check the device simultaneously. Supplemental oxygen can conceal ventilation failure on the saturation display.'],['Handover the trend, intervention, response and next action—not the best saturation of the shift.'],'must',['aha-bls','aha-als']),
s('oxygen-supply','Make the plan survive a transfer',['A concentrator needs power; a cylinder contains finite gas. Check regulator, usable volume, actual device gas draw, reserve, backup, monitoring and the accepting team. “There is a cylinder” is not an adequate transfer plan.','Practice arithmetic: 240 usable litres at a total draw of 8 L/min lasts 30 minutes before additional reserve and delays. Real calculations must use the device’s actual consumption and an approved reserve; a high-flow system’s total gas draw is not necessarily its oxygen flow.'],['Secure cylinders in approved holders. Keep oxygen away from ignition sources and oils/grease.','If the planned support cannot be sustained in transit, escalate the transport arrangements before departure.'],'must',['rch-oxygen','course']),
s('oxygen-depth','Why a labelled concentration is not enough',['Fit, inspiratory demand and entrained air change delivery. Compare the observed response after a device change. A printed setting describes what the system is asked to do; it does not prove the child is receiving effective support.'],[],'good',['rch-oxygen']),
s('oxygen-enrichment','A system reliability thought experiment',['List where oxygen could fail between its source and the child. Now add the journey to a referral centre. Which failure would be invisible if the handover contained only a saturation value? Use your list in a supervised equipment walk-through.'],[],'nice',['course','rch-oxygen'])],
reflection:'Explain your oxygen plan in one sentence. What would make you escalate despite an SpO₂ inside target?'};
oxygen.questions=decisions(oxygen,[
['plan','Handover says “oxygen by mask.” What addition makes it actionable?','A referral note records 3 L/min without a response plan. What needs clarification?','Target, interface and reassessment/escalation plan~Defines the goal and what to do if support fails.','Target saturation alone~Necessary but leaves delivery and failure response unclear.','Device brand and supplier~Useful equipment information does not define clinical goals.','Flow until the next ward round~A fixed flow without response checks can conceal deterioration.','Link an intervention to a measurable response and next action.'],
['target','A healthy 10-week-old with bronchiolitis has persistent SpO₂ 89%. Under the NICE example, how should this be interpreted?','A healthy 8-month-old with bronchiolitis repeatedly reads 88% with a good signal. How does the NICE example apply?','Below the oxygen-treatment threshold for this group~At least six weeks old with persistent saturation below 90%.','Wait until saturation is below 85%~This is lower than the cited threshold.','Apply an adult target without considering diagnosis~The recommendation is condition- and age-specific.','This value alone mandates intubation~Oxygen need and invasive-support need are different decisions.','Use the recommendation for this patient group; assess severity separately.'],
['target','A 4-week-old with bronchiolitis has persistent SpO₂ 91%. Which qualifier matters?','A 9-month-old with bronchiolitis and underlying disease has persistent SpO₂ 91%. Which qualifier matters?','Younger infants or comorbidity use a higher treatment threshold~NICE uses below 92% for these groups; individualized specialist targets can also matter.','The healthy older-infant rule always applies~Age and underlying disease change the recommendation.','91% excludes severe respiratory illness~Saturation does not determine overall severity.','Every infant needs the same device flow~Delivery must fit the child, system and response.','Thresholds require their age, condition and comorbidity qualifiers.'],
['device','A simple mask is running at 1 L/min. Which safety issue needs correction?','Oxygen demand falls and a mask flow is reduced below its printed minimum. What now?','Restore a suitable device/flow plan that prevents rebreathing~Use the specified minimum or a suitable alternative interface.','Keep the flow if the mask is comfortable~Comfort does not exclude gas rebreathing.','Tighten the mask without changing flow~A tighter seal does not provide fresh-gas clearance.','Add humidification to compensate~Water does not replace adequate fresh gas.','Operate the delivery system within its device requirements.',true],
['device','The reservoir bag empties on every inspiration. What is the immediate response?','Distress increases after a reservoir mask change and its bag remains collapsed. Which check comes first?','Supply, flow, tubing and mask function while supporting the child~Correct a possible delivery failure without postponing clinical support.','Assume efficient oxygen uptake~Complete collapse may indicate insufficient gas supply.','Wait for a blood gas before touching equipment~A visible delivery problem needs prompt attention.','Tape over the device valves~Unplanned modifications can obstruct safe gas movement.','Treat the child while checking why gas delivery is inadequate.',true],
['response','SpO₂ rises from 87% to 94%, but drowsiness and poor air entry develop. What now?','SpO₂ is 96% on oxygen while breaths become shallow and consciousness falls. What matters most?','Urgently assess ventilation and escalate support~Oxygen can preserve saturation during ventilation failure.','Reduce observations after reaching target~The clinical trend contradicts recovery.','Increase oxygen alone and defer airway review~Oxygen does not correct inadequate ventilation.','Wait for cyanosis to confirm deterioration~That is a late sign and may be masked by oxygen.','Breathing, consciousness and perfusion are treatment outcomes too.',true],
['supply','A source has 240 usable L and total consumption is 8 L/min. What is its theoretical duration before extra reserves?','There are 180 usable L with total consumption of 6 L/min. What is the theoretical duration before extra reserves?','30 minutes~Divide usable volume by total flow.','20 minutes~Recalculate volume divided by flow; reserve is considered separately.','40 minutes~This overestimates available duration.','60 minutes~This doubles the available duration.','This is arithmetic practice; real transport plans include reserve, delays and device consumption.'],
['supply','A concentrator-dependent child must cross an area without mains power. What must be arranged?','The ward has repeated power failures while a child needs concentrator oxygen. Which plan is safest?','A sufficient backup source and supported escalation plan~Therapy must remain deliverable when the source fails.','One saturation check before departure~A single reading does not guarantee ongoing supply.','Larger nasal prongs~Interface size cannot restore absent gas.','Routine referral paperwork alone~Administrative completion does not sustain respiratory support.','Plan the resource needed to sustain the intervention.',true],
['device','A Venturi adapter specifies gas flow. What preserves its intended performance?','Bedding is covering an air-entrainment adapter. What correction matters?','Use specified flow and keep entrainment ports clear~The mixture depends on controlled entrainment.','Block ports to increase concentration~This defeats the designed performance.','Use the setting from any simple mask~Systems have different operating requirements.','Infer FiO₂ from a nasal-prong chart~That does not describe this device.','Understand how the system generates its mixture.'],
['response','Which record best supports a decision after oxygen is changed?','Which handover best demonstrates whether oxygen therapy is working?','Timed settings and trends in effort, alertness, SpO₂ and perfusion~Connects the intervention to the whole-child response.','Current saturation without previous values~This conceals trajectory.','Device name without flow or target~It does not specify delivered support or its purpose.','The highest saturation of the shift~A best value may conceal later deterioration.','A treatment-response record should enable the next clinician to act.']]);
