export const sources = [
 { id:'aha-bls', title:'Pediatric Basic Life Support', organization:'AHA / AAP', version:'2025 guidelines', url:'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/pediatric-basic-life-support', scope:'Online recommendations: respiratory deterioration, inadequate breathing with a pulse, scope and ventilation rate.', caveat:'Infant/child guidance; newborn resuscitation is a separate pathway. Not a substitute for supervised resuscitation training.' },
 { id:'aha-als', title:'Pediatric Advanced Life Support', organization:'AHA / AAP', version:'2025 guidelines', url:'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/pediatric-advanced-life-support', scope:'Online respiratory support and advanced-airway confirmation recommendations, including low pulmonary blood flow caveat.', caveat:'Use local team responsibilities and current resuscitation pathways. Drug dosing is outside this module.' },
 { id:'nice', title:'Bronchiolitis: diagnosis and management', organization:'NICE', version:'NG9; oxygen recommendations updated 2021', url:'https://www.nice.org.uk/guidance/ng9/chapter/Recommendations', scope:'Recommendations 1.4.4 and oxygen-related age/comorbidity distinctions; guideline recommendations page/PDF.', caveat:'UK bronchiolitis guidance, used as an explicitly labelled example; not a universal pediatric oxygen target.' },
 { id:'rch-oxygen', title:'Oxygen delivery', organization:'Royal Children’s Hospital Melbourne', version:'Web nursing guideline, accessed 15 September 2026', url:'https://www.rch.org.au/rchcpg/hospital_clinical_guideline_index/Oxygen_delivery/', scope:'Device characteristics, nasal-prong limits, simple-mask minimum flow and oxygen safety sections.', caveat:'Hospital/device-specific practice. Minimum flows vary by mask: check the actual manufacturer instructions and local policy.' },
 { id:'rch-hfnc', title:'High flow nasal prong therapy', organization:'Royal Children’s Hospital Melbourne', version:'November 2021 web guideline', url:'https://www.rch.org.au/rchcpg/hospital_clinical_guideline_index/High_flow_nasal_prong_(HFNP)_therapy/', scope:'Interface, weight-based flow, early response, escalation, care and cessation sections.', caveat:'A named hospital protocol example, not an India-wide protocol. Device and clinical setting matter; escalation must be immediate for deterioration.' },
 { id:'palicc', title:'PALICC-2 executive summary', organization:'International PALICC-2 group', version:'2023; Pediatric Critical Care Medicine 24:143–168', url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9848214/', scope:'Indexed executive-summary recommendations 3.2–3.4, 3.9–3.10 and section 6 monitoring; full-page access was intermittent.', caveat:'PARDS recommendations, many conditional and based on low/very-low-certainty evidence. Full source and local PICU review required before operational adoption.' },
 { id:'fda', title:'Pulse oximeters: benefits and limitations', organization:'US FDA', version:'Web page including January 2025 draft-guidance notice', url:'https://www.fda.gov/medical-devices/products-and-medical-procedures/pulse-oximeters', scope:'Clinical limitations, skin pigmentation, poor perfusion and device-reading interpretation.', caveat:'The 2025 draft is not presented as final device guidance. Clinical findings remain essential.' },
 { id:'who', title:'Oxygen therapy for children', organization:'World Health Organization', version:'2016 handbook', url:'https://www.who.int/publications/i/item/9789241549554', scope:'Publication landing page and identity checked; entire handbook not inspected in this build.', caveat:'Further reading; does not independently verify all course claims or local protocols.' },
 { id:'course', title:'OxyVent learning design and original scenarios', organization:'Vikkypaedia', version:'Educational revision 2026.09.16.2', url:'#about', scope:'Original fictional scenarios, learning rules and arithmetic examples; clinical claims additionally cite relevant guidance.', caveat:'Author-created educational exercises. Not clinical research, accreditation or independent expert approval.' }
].map(s => ({...s, checkedOn:['aha-bls','aha-als','fda','rch-oxygen','rch-hfnc','course'].includes(s.id)?'2026-09-16':'2026-09-15', access:'Public source; read scope described above'}));
